//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThirdParty.Tests.iVectorConnect {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BookABedRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BookABedRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThirdParty.Tests.iVectorConnect.BookABedRes", typeof(BookABedRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: http://bookabedtest.ivectorconnect.co.uk/ivectorconnect.ashx
        ///
        ///**HEADERS**
        ///
        ///Content-Type: application/x-www-form-urlencoded
        ///Timeout: 1
        ///
        ///
        ///**REQUEST**
        ///
        ///&lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;PropertySearchRequest xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;LoginDetails&gt;
        ///    &lt;Login&gt;agendas&lt;/Login&gt;
        ///    &lt;Password&gt;group&lt;/Password&gt;
        ///    &lt;AgentReference&gt;10275&lt;/AgentReference&gt;
        ///    &lt;SellingCurrencyID&gt;1&lt;/SellingCurrencyID&gt;
        ///  &lt;/LoginDetails&gt;
        ///  &lt;PropertyRef [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLog {
            get {
                return ResourceManager.GetString("RequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;PropertySearchResponse&gt;
        ///  &lt;ReturnStatus&gt;
        ///    &lt;Success&gt;true&lt;/Success&gt;
        ///    &lt;Exceptions/&gt;
        ///  &lt;/ReturnStatus&gt;
        ///  &lt;PropertyResults&gt;
        ///    &lt;PropertyResult&gt;
        ///      &lt;BookingToken&gt;77XHIv7Wgmjcz5UZVg6hc5tJePeitsFIzstwLfcKR3U=&lt;/BookingToken&gt;
        ///      &lt;PropertyReferenceID&gt;673&lt;/PropertyReferenceID&gt;
        ///      &lt;GeographyLevel1ID&gt;19&lt;/GeographyLevel1ID&gt;
        ///      &lt;GeographyLevel2ID&gt;26&lt;/GeographyLevel2ID&gt;
        ///      &lt;GeographyLevel3ID&gt;133&lt;/GeographyLevel3ID&gt;
        ///      &lt;RoomTypes&gt;
        ///        &lt;RoomType&gt;
        ///          &lt;Se [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResponseXML {
            get {
                return ResourceManager.GetString("ResponseXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;673&quot; CC=&quot;1&quot; PRBID=&quot;1&quot; RT=&quot;Twin Deluxe&quot; MBC=&quot;3&quot; AMT=&quot;250.0&quot; TPR=&quot;77XHIv7Wgmjcz5UZVg6hc5tJePeitsFIzstwLfcKR3U=|G879hu9y9H9y9GYJ54Tvf64=&quot; DSC=&quot;0&quot; COM=&quot;0&quot; DP=&quot;false&quot; NPA=&quot;0&quot; NRF=&quot;false&quot; FIXPR=&quot;false&quot; FREEC=&quot;false&quot; RQ=&quot;false&quot; PLA=&quot;false&quot; PLR=&quot;false&quot; MSP=&quot;0&quot;&gt;&lt;Cs /&gt;&lt;/Result&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;673&quot; CC=&quot;1&quot; PRBID=&quot;2&quot; RT=&quot;Double Deluxe&quot; MBC=&quot;3&quot; AMT=&quot;280.0&quot; TPR=&quot;77XHIv7Wgmjcz5UZVg6hc5tJePeitsFIzstwLfcKR3U=|30ea0uji5350043759oot09re0t=&quot; DSC=&quot;0&quot; COM=&quot;0&quot; DP=&quot;false&quot; NPA=&quot;0&quot; NRF=&quot;false&quot; FIXPR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransformedResultXML {
            get {
                return ResourceManager.GetString("TransformedResultXML", resourceCulture);
            }
        }
    }
}
