//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVectorOne.Tests.JonView {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JonViewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JonViewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iVectorOne.Tests.JonView.JonViewRes", typeof(JonViewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: http://www.jonview.com/ws/services/Jonviewhostserver_xmlN_cst_xmlServiceBindingImpl?actioncode=HOSTXML&amp;clientlocseq=25788&amp;userid=BABHOST&amp;password=HANGZHOU&amp;message=&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;message&gt;&lt;actionseg&gt;CT&lt;/actionseg&gt;&lt;searchseg&gt;&lt;prodtypecode&gt;FIT&lt;/prodtypecode&gt;&lt;searchtype&gt;CITY&lt;/searchtype&gt;&lt;citycode&gt;MAD_12&lt;/citycode&gt;&lt;startdate&gt;01-Sep-2021&lt;/startdate&gt;&lt;duration&gt;5&lt;/duration&gt;&lt;status&gt;AVAILABLE&lt;/status&gt;&lt;displayname&gt;Y&lt;/displayname&gt;&lt;displaynamedetails&gt;Y&lt;/displaynamedetails&gt;&lt;displayroomconf&gt;Y&lt;/d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLog {
            get {
                return ResourceManager.GetString("RequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;message&gt;&lt;actionseg&gt;&lt;actioncode&gt;CT&lt;/actioncode&gt;&lt;status&gt;C&lt;/status&gt;&lt;errmsg&gt;317&lt;/errmsg&gt;&lt;/actionseg&gt;&lt;alternatelistseg&gt;&lt;listrecord&gt;&lt;prodcode&gt;ASESQ&lt;/prodcode&gt;&lt;status&gt;A&lt;/status&gt;&lt;productname&gt;ASPEN SQUARE - FIREPLACE STUDIO&lt;/productname&gt;&lt;prodtypecode&gt;FIT&lt;/prodtypecode&gt;&lt;dynamicrateproduct&gt;N&lt;/dynamicrateproduct&gt;&lt;dynamicinfo/&gt;&lt;jrating&gt;JJJ&lt;/jrating&gt;&lt;suppliercode&gt;ASESQ&lt;/suppliercode&gt;&lt;currencycode&gt;USD&lt;/currencycode&gt;&lt;dayprice&gt;362.94/362.94/362.94&lt;/dayprice&gt;&lt;dayavail&gt;999&lt;/dayavail&gt;&lt;pro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchResponse {
            get {
                return ResourceManager.GetString("SearchResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;ASESQ&quot; CC=&quot;USD&quot; PRBID=&quot;1&quot; RTC=&quot;FIREPLACE STUDIO&quot; RT=&quot;FIREPLACE STUDIO, 1 KING or 1 KING, 1 QUEEN SOFA or 2 TWIN * D/T&quot; MBC=&quot;RO&quot; AMT=&quot;1088.82&quot; TPR=&quot;ASESQ_362.94/362.94/362.94&quot; DSC=&quot;0&quot; COM=&quot;0&quot; DP=&quot;false&quot; NPA=&quot;0&quot; NRF=&quot;false&quot; FIXPR=&quot;false&quot; FREEC=&quot;false&quot; RQ=&quot;false&quot; PLA=&quot;false&quot; PLR=&quot;false&quot; MSP=&quot;0&quot;&gt;&lt;Cs /&gt;&lt;/Result&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;ASESQ&quot; CC=&quot;USD&quot; PRBID=&quot;1&quot; RTC=&quot;1 BEDROOM CONDO&quot; RT=&quot;1 BEDROOM CONDO, 1 KING, 1 QUEEN SOFA * D/T&quot; MBC=&quot;RO&quot; AMT=&quot;1182.42&quot; TPR=&quot;ASESQ1_394.14/394.14/394.14&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransformedResult {
            get {
                return ResourceManager.GetString("TransformedResult", resourceCulture);
            }
        }
    }
}
