//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVectorOne.Suppliers.TPIntegrationTests.AmadeusHotels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AmadeusHotelsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AmadeusHotelsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThirdParty.Suppliers.TPIntegrationTests.AmadeusHotels.AmadeusHotelsRes", typeof(AmadeusHotelsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: https://nodeD1.test.webservices.amadeus.com/1ASIWIVRINS
        ///
        ///**HEADERS**
        ///
        ///action: http://webservices.amadeus.com/Hotel_MultiSingleAvailability_10.0
        ///SOAPAction: http://webservices.amadeus.com/Hotel_MultiSingleAvailability_10.0
        ///Accept-Encoding: gzip
        ///Content-Type: text/xml
        ///Timeout: 300
        ///
        ///
        ///**REQUEST**
        ///
        ///&lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///  &lt;soap:Header xmlns:awsse=&quot;http://xml.amadeus.com/2010/06/Session_v3&quot;&gt;
        ///    &lt;ses:Session TransactionStatusCode=&quot;Start&quot; xmlns:s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLog {
            get {
                return ResourceManager.GetString("RequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;soapenv:Envelope xmlns:soapenv=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:awsse=&quot;http://xml.amadeus.com/2010/06/Session_v3&quot; xmlns:wsa=&quot;http://www.w3.org/2005/08/addressing&quot;&gt;
        ///    &lt;soapenv:Header&gt;
        ///        &lt;wsa:To&gt;http://www.w3.org/2005/08/addressing/anonymous&lt;/wsa:To&gt;
        ///        &lt;wsa:From&gt;
        ///            &lt;wsa:Address&gt;https://nodeD1.test.webservices.amadeus.com/1ASIWXXXYYY&lt;/wsa:Address&gt;
        ///        &lt;/wsa:From&gt;
        ///        &lt;wsa:Action&gt;http://webservices.amadeus.com/A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;GU_GUBERADV&quot; CC=&quot;EUR&quot; RTC=&quot;A2S&quot; RT=&quot;Standard Twin&quot; MBC=&quot;3&quot; AMT=&quot;902.50&quot; TPR=&quot;00000001|RAC||3&quot; DSC=&quot;0&quot; AR=&quot;1&quot; COM=&quot;0&quot; DP=&quot;false&quot; NPA=&quot;0&quot; NRF=&quot;false&quot; FIXPR=&quot;false&quot; FREEC=&quot;false&quot; TPRC=&quot;RAC&quot; RQ=&quot;false&quot; PLA=&quot;false&quot; PLR=&quot;false&quot; MSP=&quot;0&quot;&gt;&lt;Cs /&gt;&lt;/Result&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;GU_GUBERADV&quot; CC=&quot;EUR&quot; RTC=&quot;A2S&quot; RT=&quot;Standard Triple&quot; MBC=&quot;3&quot; AMT=&quot;1105.00&quot; TPR=&quot;00000002|RAC||3&quot; DSC=&quot;0&quot; AR=&quot;1&quot; COM=&quot;0&quot; DP=&quot;false&quot; NPA=&quot;0&quot; NRF=&quot;false&quot; FIXPR=&quot;false&quot; FREEC=&quot;false&quot; TPRC=&quot;RAC&quot; RQ=&quot;false&quot; PLA=&quot;false&quot; PLR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransformedResponse {
            get {
                return ResourceManager.GetString("TransformedResponse", resourceCulture);
            }
        }
    }
}
