//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVectorOne.Tests.Bonotel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BonotelRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BonotelRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iVectorOne.Tests.Bonotel.BonotelRes", typeof(BonotelRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: http://xmltest.bonotel.com/bonotelapps/bonotel/reservation/GetAvailability.do
        ///
        ///**HEADERS**
        ///
        ///Content-Type: text/xml
        ///Host: xmltest.bonotel.com
        ///Content-Length: 569
        ///Connection: Close
        ///Timeout: 58
        ///
        ///**REQUEST**
        ///
        ///&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;availabilityRequest&gt;&lt;control&gt;&lt;userName&gt;trvlpths_xml&lt;/userName&gt;&lt;passWord&gt;trvl20p0809&lt;/passWord&gt;&lt;/control&gt;&lt;checkIn&gt;01-Sep-2021&lt;/checkIn&gt;&lt;checkOut&gt;06-Sep-2021&lt;/checkOut&gt;&lt;noOfRooms&gt;1&lt;/noOfRooms&gt;&lt;noOfNights&gt;5&lt;/noOfNights&gt;&lt;city&gt;MAD_12&lt;/city&gt;&lt;hotelCodes&gt;&lt;hot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLog {
            get {
                return ResourceManager.GetString("RequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;availabilityResponse status=&quot;Y&quot;&gt;
        ///&lt;hotelList&gt;
        ///	&lt;hotel&gt;
        ///		&lt;hotelCode&gt;2343&lt;/hotelCode&gt;
        ///		&lt;name&gt;Seralago Hotel and Suites&lt;/name&gt;
        ///		&lt;address&gt;5678 West Irlo Bronson Memorial Highway&lt;/address&gt;
        ///		&lt;city&gt;Kissimmee&lt;/city&gt;
        ///		&lt;stateProvince&gt;Florida&lt;/stateProvince&gt;
        ///		&lt;country&gt;USA&lt;/country&gt;
        ///		&lt;postalCode&gt;34746&lt;/postalCode&gt;
        ///		&lt;rateCurrencyCode&gt;USD&lt;/rateCurrencyCode&gt;
        ///		&lt;shortDescription&gt;The Seralago Hotel and Suites Main Gate East is located in Kissimmee, FL, and stands a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResponseXML {
            get {
                return ResourceManager.GetString("ResponseXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;2343&quot; CC=&quot;USD&quot; PRBID=&quot;1&quot; RT=&quot;Double Poolview&quot; RTC=&quot;0&quot; MBC=&quot;1&quot; AD=&quot;0&quot; CH=&quot;0&quot; hlpCHA=&quot;0&quot; INF=&quot;0&quot; AMT=&quot;270.72&quot; TPR=&quot;158846|10798|4|USD|1|0&quot; NRF=&quot;0&quot; /&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;2343&quot; CC=&quot;USD&quot; PRBID=&quot;1&quot; RT=&quot;Double Poolview&quot; RTC=&quot;0&quot; MBC=&quot;1&quot; AD=&quot;0&quot; CH=&quot;0&quot; hlpCHA=&quot;0&quot; INF=&quot;0&quot; AMT=&quot;270.72&quot; TPR=&quot;158847|10798|5|USD|1|0&quot; NRF=&quot;0&quot; /&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;2343&quot; CC=&quot;USD&quot; PRBID=&quot;1&quot; RT=&quot;Double Standard&quot; RTC=&quot;0&quot; MBC=&quot;1&quot; AD=&quot;0&quot; CH=&quot;0&quot; hlpCHA=&quot;0&quot; INF=&quot;0&quot; AMT=&quot;225.60&quot; TPR=&quot;158841|9113|4|USD|1|0&quot; NRF=&quot;0&quot; /&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransformedResultXML {
            get {
                return ResourceManager.GetString("TransformedResultXML", resourceCulture);
            }
        }
    }
}
