//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThirdParty.CSSuppliers.Miki {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MikiRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MikiRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThirdParty.CSSuppliers.Miki.MikiRes", typeof(MikiRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;dailyB2BPasswords&gt;
        ///    &lt;agentCode&gt;PTH003&lt;/agentCode&gt;
        ///    &lt;dailyPasswords&gt;
        ///        &lt;dailyPassword&gt;
        ///            &lt;sendDate&gt;2019-04-22&lt;/sendDate&gt;
        ///            &lt;password&gt;12L71M40T41S10T03W65&lt;/password&gt;
        ///        &lt;/dailyPassword&gt;
        ///        &lt;dailyPassword&gt;
        ///            &lt;sendDate&gt;2019-04-23&lt;/sendDate&gt;
        ///            &lt;password&gt;37E83L71A19A92F28S33&lt;/password&gt;
        ///        &lt;/dailyPassword&gt;
        ///        &lt;dailyPassword&gt;
        ///            &lt;sendDate&gt;2019-04-24&lt;/sendDate&gt;
        ///            &lt;password&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccessCodes_BookABed {
            get {
                return ResourceManager.GetString("AccessCodes_BookABed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubProduct Code|Description|Max Pax|Min Pax|Max Adults|Min Adults|Max Child Age 3 - 12|Min Child Age 3 - 12|Max child Age 0 - 2|Min child Age 0 - 2
        ///00001|Twin room|2|2|2|1|1|0|0|0|Chambre а lits jumeaux (2 personnes)|Habitaciуn twin (2 camas)
        ///00002|Single room|1|1|1|1|0|0|0|0|Chambre individuelle|Habitaciуn individual
        ///00003|Triple room|3|3|3|1|2|0|0|0|Chambre triple|Habitaciуn triple
        ///00004|Twin room (sole use)|1|1|1|1|0|0|0|0|Chambre а lits jumeaux (1 personne|Habitaciуn twin (uso individual)
        ///01001|Dou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RoomTypes {
            get {
                return ResourceManager.GetString("RoomTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubProduct Code|Description|Max Pax|Min Pax|Max Adults|Min Adults|Max Child Age 3 - 12|Min Child Age 3 - 12|Max child Age 0 - 2|Min child Age 0 - 2
        ///00001|Twin room|2|2|2|1|1|0|0|0|Chambre а lits jumeaux (2 personnes)|Habitaciуn twin (2 camas)
        ///00002|Single room|1|1|1|1|0|0|0|0|Chambre individuelle|Habitaciуn individual
        ///00003|Triple room|3|3|3|1|2|0|0|0|Chambre triple|Habitaciуn triple
        ///00004|Twin room (sole use)|1|1|1|1|0|0|0|0|Chambre а lits jumeaux (1 personne|Habitaciуn twin (uso individual)
        ///01001|Dou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RoomTypesWithTranslations {
            get {
                return ResourceManager.GetString("RoomTypesWithTranslations", resourceCulture);
            }
        }
    }
}
