//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThirdParty.Tests.ExpediaRapid {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExpediaRapidRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExpediaRapidRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThirdParty.Tests.ExpediaRapid.ExpediaRapidRes", typeof(ExpediaRapidRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: https://test.ean.com/2.3/properties/availability?checkin=2021-09-01&amp;checkout=2021-09-06&amp;currency=GBP&amp;language=en-US&amp;country_code=GB&amp;sales_channel=agent_tool&amp;sales_environment=hotel_only&amp;sort_type=preferred&amp;rate_plan_count=250&amp;payment_terms=EAC&amp;partner_point_of_sale=EAC_SA&amp;billing_terms=&amp;rate_option=net_rates&amp;occupancy=1&amp;property_id=102245
        ///
        ///**HEADERS**
        ///
        ///Timeout: 58
        ///
        ///
        ///**REQUEST**
        ///
        ///URL: https://test.ean.com/2.3/properties/availability?checkin=2021-09-01&amp;checkout=2021-09-06&amp;currency=GBP&amp;language=e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLog {
            get {
                return ResourceManager.GetString("RequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;property_id&quot;:&quot;2232519&quot;,&quot;rooms&quot;:[{&quot;id&quot;:&quot;201200473&quot;,&quot;room_name&quot;:&quot;Double Room, Sea View&quot;,&quot;rates&quot;:[{&quot;id&quot;:&quot;274263561&quot;,&quot;available_rooms&quot;:3,&quot;refundable&quot;:false,&quot;fenced_deal&quot;:false,&quot;fenced_deal_available&quot;:false,&quot;deposit_required&quot;:false,&quot;merchant_of_record&quot;:&quot;expedia&quot;,&quot;amenities&quot;:{&quot;2192&quot;:{&quot;id&quot;:2192,&quot;name&quot;:&quot;Free WiFi&quot;},&quot;2109&quot;:{&quot;id&quot;:2109,&quot;name&quot;:&quot;Free self parking&quot;},&quot;2206&quot;:{&quot;id&quot;:2206,&quot;name&quot;:&quot;Half Board&quot;}},&quot;links&quot;:{&quot;payment_options&quot;:{&quot;method&quot;:&quot;GET&quot;,&quot;href&quot;:&quot;/2.3/properties/2232519/payment-options?token=REhZAQsABQMGQhMHU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResponseString {
            get {
                return ResourceManager.GetString("ResponseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;2232519&quot; TPK=&quot;2232519&quot; CC=&quot;GBP&quot; PRBID=&quot;1&quot; RTC=&quot;201200473|274263561|37341&quot; RT=&quot;Double Room, Sea View, 2 Twin Beds&quot; MBC=&quot;RO&quot; AD=&quot;1&quot; AMT=&quot;786.26&quot; TPR=&quot;0cc65639-211e-446b-8d5f-2b28a480bbeb|/2.3/properties/2232519/rooms/201200473/rates/274263561/price-check?token=B~OjogZCw0NRkyAQ9PYWUCZ38nD2gCCVAIS1YAFAUFITJUAVQCGAldTgRSc2dzJGNkHQFXXFwEAFUBFFIEB1cbBlBVBh4OUgEDGlYCXFAFUQQNUwVTBz5BAglRBgQHDVUVAQYCURpVV1sJGV1RAwsfAF1eBFRTVAsEBgUEVDJQA1QBBwVZFFMFVVUMVFMETFEFAVUUBVUPWBVYVlkAGVQCCwdWBgdRVwFVABM1U [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransformedResultXML {
            get {
                return ResourceManager.GetString("TransformedResultXML", resourceCulture);
            }
        }
    }
}
