//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVectorOne.Tests.GoGlobal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GoGlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GoGlobalRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iVectorOne.Tests.GoGlobal.GoGlobalRes", typeof(GoGlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: http://xml.cloud.goglobal.travel/XMLWebService.asmx
        ///
        ///**HEADERS**
        ///
        ///Timeout: 100
        ///
        ///
        ///**REQUEST**
        ///
        ///&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;soap:Envelope xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;&lt;soap:Body&gt;&lt;MakeRequest xmlns=&quot;http://www.goglobal.travel/&quot;&gt;&lt;requestType&gt;11&lt;/requestType&gt;&lt;xmlRequest&gt;&lt;![CDATA[&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;Root xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLogs {
            get {
                return ResourceManager.GetString("RequestLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;&lt;soap:Body&gt;&lt;MakeRequestResponse xmlns=&quot;http://www.goglobal.travel/&quot;&gt;&lt;MakeRequestResult&gt;{&quot;Header&quot;:{&quot;Agency&quot;:&quot;123872&quot;,&quot;User&quot;:&quot;INTUITIVEXMLTEST&quot;,&quot;Password&quot;:&quot;NYR4JTGAN25H&quot;,&quot;Operation&quot;:&quot;HOTEL_SEARCH_RESPONSE&quot;,&quot;OperationType&quot;:&quot;Response&quot;,&quot;Stats&quot;:{&quot;HotelQty&quot;:1,&quot;ResultsQty&quot;:4}},&quot;Hotels&quot;:[{&quot;HotelName&quot;:&quot;MIRAY&quot;,&quot;Hot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;58433&quot; TPK=&quot;58433&quot; CC=&quot;EUR&quot; RT=&quot;Twin/Double room&quot; MBC=&quot;HB&quot; AMT=&quot;436.0&quot; TPR=&quot;311011/2010997739251820518/0&quot; DSC=&quot;0&quot; COM=&quot;0&quot; DP=&quot;false&quot; NPA=&quot;0&quot; NRF=&quot;false&quot; FIXPR=&quot;false&quot; FREEC=&quot;false&quot; RQ=&quot;false&quot; PLA=&quot;false&quot; PLR=&quot;false&quot; MSP=&quot;0&quot;&gt;&lt;Cs&gt;&lt;C SD=&quot;&quot; ED=&quot;&quot; AMT=&quot;65.40&quot; /&gt;&lt;C SD=&quot;2022-06-21T00:00:00&quot; ED=&quot;2022-06-22T00:00:00&quot; AMT=&quot;187.48&quot; /&gt;&lt;C SD=&quot;2022-06-23T00:00:00&quot; ED=&quot;2021-08-31T00:00:00&quot; AMT=&quot;313.92&quot; /&gt;&lt;/Cs&gt;&lt;/Result&gt;&lt;Result MID=&quot;58433&quot; TPK=&quot;58433&quot; CC=&quot;EUR&quot; RT=&quot;FAMILY ROOM 2 BEDROOMS&quot; MBC=&quot;BB&quot; AMT=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransformedResponse {
            get {
                return ResourceManager.GetString("TransformedResponse", resourceCulture);
            }
        }
    }
}
