// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------


using System.Diagnostics;

namespace ThirdParty.CSSuppliers.SunHotels
{

    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    internal class SunHotelsRes
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SunHotelsRes() : base()
        {
        }

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("ThirdParty.CSSuppliers.Sunhotels.SunHotelsRes", typeof(SunHotelsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;getRoomTypesResult xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///    &lt;roomTypes&gt;
        ///        &lt;roomType&gt;
        ///            &lt;id&gt;1&lt;/id&gt;
        ///            &lt;name&gt;Single room&lt;/name&gt;
        ///            &lt;sharedRoom&gt;0&lt;/sharedRoom&gt;
        ///            &lt;sharedFacilities xsi:nil=&quot;true&quot; /&gt;
        ///        &lt;/roomType&gt;
        ///        &lt;roomType&gt;
        ///            &lt;id&gt;2&lt;/id&gt;
        ///            &lt;name&gt;Single room - Sea View&lt;/name&gt;
        ///            &lt;sharedRoom&gt;0&lt;/sharedRoom&gt;
        ///            &lt;sharedFacilities xsi:nil=&quot;true&quot; /&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SunHotelsRoomType
        {
            get
            {
                return ResourceManager.GetString("SunHotelsRoomType", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        /// &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;&gt;
        ///    &lt;xsl:output method=&quot;xml&quot;/&gt;
        /// 	&lt;xsl:param name=&quot;Currency&quot; /&gt;
        ///    &lt;xsl:template match=&quot;/&quot;&gt;
        ///    
        /// 	&lt;Results&gt;
        /// 
        /// 		&lt;xsl:for-each select=&quot;/Results/Guests/Room&quot;&gt;
        /// 
        /// 			&lt;xsl:variable name=&quot;Adults&quot; select=&quot;Adults&quot; /&gt;
        /// 			&lt;xsl:variable name=&quot;Children&quot; select=&quot;Children&quot; /&gt;
        /// 			&lt;xsl:variable name=&quot;Infants&quot; select= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SunHotelsSearchXSL
        {
            get
            {
                return ResourceManager.GetString("SunHotelsSearchXSL", resourceCulture);
            }
        }
    }
}