//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVectorOne.Tests.DerbySoft {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DerbySoftRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DerbySoftRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iVectorOne.Tests.DerbySoft.DerbySoftRes", typeof(DerbySoftRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;hotelId&quot;: &quot;GOH101&quot;,
        ///    &quot;stayRange&quot;: {
        ///        &quot;checkin&quot;: &quot;2021-12-25&quot;,
        ///        &quot;checkout&quot;: &quot;2021-12-28&quot;
        ///    },
        ///    &quot;roomCriteria&quot;: {
        ///        &quot;roomCount&quot;: 1,
        ///        &quot;adultCount&quot;: 2,
        ///        &quot;childCount&quot;: 0
        ///    },
        ///    &quot;roomRates&quot;: [
        ///        {
        ///            &quot;roomId&quot;: &quot;T2&quot;,
        ///            &quot;rateId&quot;: &quot;BAR&quot;,
        ///            &quot;currency&quot;: &quot;CNY&quot;,
        ///            &quot;inventory&quot;: 9,
        ///            &quot;amountAfterTax&quot;: [
        ///                120.0,
        ///                120.0,
        ///                120.0
        ///            ],
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BookingEngineResponse {
            get {
                return ResourceManager.GetString("BookingEngineResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;GOH101&quot; CC=&quot;CNY&quot; PRBID=&quot;1&quot; RTC=&quot;T2&quot; RT=&quot;&quot; MBC=&quot;RO&quot; AMT=&quot;360.0&quot; TPR=&quot;{{&amp;quot;SearchToken&amp;quot;:&amp;quot;2a774834-63a2-4a29-a699-7706e4bb1f42&amp;quot;,&amp;quot;PreBookToken&amp;quot;:&amp;quot;&amp;quot;,&amp;quot;PreBookBookingToken&amp;quot;:&amp;quot;&amp;quot;,&amp;quot;Cancellations&amp;quot;:[{{&amp;quot;StartDate&amp;quot;:&amp;quot;2021-09-01T16:00:00&amp;quot;,&amp;quot;EndDate&amp;quot;:&amp;quot;2021-09-02T05:59:00&amp;quot;,&amp;quot;Amount&amp;quot;:120.0}},{{&amp;quot;StartDate&amp;quot;:&amp;quot;2021-09-02T06:00:00&amp;quot;,&amp;quot;EndDate&amp;quot;:&amp;quot;2099-01-01T0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BookingEngineTransofrmeResponse {
            get {
                return ResourceManager.GetString("BookingEngineTransofrmeResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: https://solo.derbysoft-test.com/bookingusbv4/availability
        ///
        ///**HEADERS**
        ///
        ///Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJUSE9NQVNDT09LIiwibmFtZSI6InRob21hc2Nvb2siLCJ0aW1lIjoiMTU5MTI4MTAwMSJ9.6639Ltop5Qo0lyhf-JxIpZcg4op8O3gpyB-tTcFx1d8
        ///Accept: application/json
        ///Accept-Encoding: gzip
        ///Content-Type: application/json
        ///Timeout: 100
        ///
        ///
        ///**REQUEST**
        ///
        ///{&quot;header&quot;:{&quot;supplierId&quot;:&quot;CLUBMEDUK&quot;,&quot;distributorId&quot;:&quot;THOMASCOOK&quot;,&quot;version&quot;:&quot;v4&quot;,&quot;token&quot;:&quot;2a774834-63a2-4a29-a699-7706e4bb1f42&quot;},&quot;hot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BookingUsbV4RequestLogs {
            get {
                return ResourceManager.GetString("BookingUsbV4RequestLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: https://solo.derbysoft-test.com/shoppingenginev4/shopping/multihotels
        ///
        ///**HEADERS**
        ///
        ///Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJUSE9NQVNDT09LIiwibmFtZSI6InRob21hc2Nvb2siLCJ0aW1lIjoiMTU5MTI4MTAwMSJ9.6639Ltop5Qo0lyhf-JxIpZcg4op8O3gpyB-tTcFx1d8
        ///Accept: application/json
        ///Accept-Encoding: gzip
        ///Content-Type: application/json
        ///Timeout: 100
        ///
        ///
        ///**REQUEST**
        ///
        ///{&quot;header&quot;:{&quot;distributorId&quot;:&quot;THOMASCOOK&quot;,&quot;version&quot;:&quot;v4&quot;,&quot;token&quot;:&quot;2a774834-63a2-4a29-a699-7706e4bb1f42&quot;},&quot;hotels&quot;:[{&quot;suppl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShoppingEngineRequestLogs {
            get {
                return ResourceManager.GetString("ShoppingEngineRequestLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;availHotels&quot;:[{&quot;stayRange&quot;:{&quot;checkin&quot;:&quot;2021-10-10&quot;,&quot;checkout&quot;:&quot;2021-10-13&quot;},&quot;availRoomRates&quot;:[{&quot;roomCriteria&quot;:{&quot;roomCount&quot;:1,&quot;adultCount&quot;:2,&quot;childCount&quot;:0,&quot;childAges&quot;:[]},&quot;inventory&quot;:1,&quot;roomId&quot;:&quot;H2&quot;,&quot;rateId&quot;:&quot;UK_Rate_Plan_PAI&quot;,&quot;currency&quot;:&quot;GBP&quot;,&quot;amountAfterTax&quot;:[287.33,287.33,287.34],&quot;mealPlan&quot;:&quot;AI&quot;},{&quot;roomCriteria&quot;:{&quot;roomCount&quot;:1,&quot;adultCount&quot;:2,&quot;childCount&quot;:0,&quot;childAges&quot;:[]},&quot;inventory&quot;:1,&quot;roomId&quot;:&quot;S2T&quot;,&quot;rateId&quot;:&quot;UK_Rate_Plan_PAI&quot;,&quot;currency&quot;:&quot;GBP&quot;,&quot;amountAfterTax&quot;:[564.0,564.0,564.0],&quot;mealPlan&quot;:&quot;AI&quot;},{&quot;ro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShoppingEngineResponse {
            get {
                return ResourceManager.GetString("ShoppingEngineResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;DBAC&quot; CC=&quot;GBP&quot; PRBID=&quot;1&quot; RTC=&quot;H2&quot; RT=&quot;&quot; MBC=&quot;AI&quot; AMT=&quot;862.00&quot; TPR=&quot;{{&amp;quot;SearchToken&amp;quot;:&amp;quot;2a774834-63a2-4a29-a699-7706e4bb1f42&amp;quot;,&amp;quot;PreBookToken&amp;quot;:&amp;quot;&amp;quot;,&amp;quot;PreBookBookingToken&amp;quot;:&amp;quot;&amp;quot;,&amp;quot;Cancellations&amp;quot;:[],&amp;quot;RoomRate&amp;quot;:{{&amp;quot;roomCriteria&amp;quot;:{{&amp;quot;roomCount&amp;quot;:1,&amp;quot;adultCount&amp;quot;:2,&amp;quot;childCount&amp;quot;:0,&amp;quot;childAges&amp;quot;:[]}},&amp;quot;inventory&amp;quot;:1,&amp;quot;roomId&amp;quot;:&amp;quot;H2&amp;quot;,&amp;quot;rateId&amp;quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShoppingEngineTransformedResponse {
            get {
                return ResourceManager.GetString("ShoppingEngineTransformedResponse", resourceCulture);
            }
        }
    }
}
