//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVectorOne.Tests.TeamAmerica {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TeamAmericaRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TeamAmericaRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iVectorOne.Tests.TeamAmerica.TeamAmericaRes", typeof(TeamAmericaRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: https://javatest.teamamericany.com:8443/TADoclit/services/TADoclit
        ///
        ///**HEADERS**
        ///
        ///Timeout: 100
        ///
        ///
        ///**REQUEST**
        ///
        ///&lt;soapenv:Envelope xmlns:xsd=&quot;http://www.wso2.org/php/xsd&quot; xmlns:soapenv=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///  &lt;soapenv:Header /&gt;
        ///  &lt;soapenv:Body&gt;
        ///    &lt;xsd:PriceSearch&gt;
        ///      &lt;xsd:UserName&gt;XMLBKBDIE&lt;/xsd:UserName&gt;
        ///      &lt;xsd:Password&gt;XXXXXX&lt;/xsd:Password&gt;
        ///      &lt;xsd:CityCode&gt;MAD_12&lt;/xsd:CityCode&gt;
        ///      &lt;xsd:ProductCode /&gt;
        ///      &lt;xsd:Type&gt;Hotel&lt;/xsd:Type&gt;
        ///      &lt;xsd:Occu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLog {
            get {
                return ResourceManager.GetString("RequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;soapenv:Envelope xmlns:soapenv=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///    &lt;soapenv:Body&gt;
        ///        &lt;xsd:PriceSearchResponse xmlns:xsd=&quot;http://www.wso2.org/php/xsd&quot;&gt;
        ///            &lt;xsd:hotelSearchResponse&gt;
        ///                &lt;xsd:body&gt;
        ///                    &lt;xsd:ProductCode&gt;SDFH21CLDD&lt;/xsd:ProductCode&gt;
        ///                    &lt;xsd:ProductType&gt;Hotel&lt;/xsd:ProductType&gt;
        ///                    &lt;xsd:TeamVendorID&gt;20017&lt;/xsd:TeamVendorID&gt;
        ///                    &lt;xsd:ProductDate&gt;20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;20017&quot; TPK=&quot;20017&quot; CC=&quot;USD&quot; PRBID=&quot;1&quot; RT=&quot;DELUXE - TWO DOUBLES&quot; MBC=&quot;EP-NO MEALS&quot; AMT=&quot;428.58&quot; TPR=&quot;SDFH21CLDD|Y|17&quot; DSC=&quot;0&quot; COM=&quot;0&quot; DP=&quot;false&quot; NPA=&quot;0&quot; NRF=&quot;false&quot; FIXPR=&quot;false&quot; FREEC=&quot;false&quot; RQ=&quot;false&quot; PLA=&quot;false&quot; PLR=&quot;false&quot; MSP=&quot;0&quot;&gt;&lt;Cs /&gt;&lt;/Result&gt;&lt;Result MID=&quot;20017&quot; TPK=&quot;20017&quot; CC=&quot;USD&quot; PRBID=&quot;1&quot; RT=&quot;DELUXE KING&quot; MBC=&quot;EP-NO MEALS&quot; AMT=&quot;428.58&quot; TPR=&quot;SDFH21CLDX|Y|17&quot; DSC=&quot;0&quot; COM=&quot;0&quot; DP=&quot;false&quot; NPA=&quot;0&quot; NRF=&quot;false&quot; FIXPR=&quot;false&quot; FREEC=&quot;false&quot; RQ=&quot;false&quot; PLA=&quot;false&quot; PLR=&quot;false&quot; MSP=&quot;0&quot;&gt;&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransformedResponse {
            get {
                return ResourceManager.GetString("TransformedResponse", resourceCulture);
            }
        }
    }
}
