//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVectorOne.Suppliers.ATI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ATIRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ATIRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iVectorOne.Suppliers.ATI.ATIRes", typeof(ATIRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABEBHA|ABEBHA-Z01|Kitchenette Smoking King bed/Refrigerator/Coffeemaker/Microwave/--SHK1-- Comp Hot Buffet Breakfast
        ///ABEBHA|ABEBHA-Z02|Non Smoking King Suite With Sofabed/Refrigerator/Coffeemaker/Microwave/--NFK1-- Comp Hot Buffet Brea
        ///ABEBHA|ABEBHA-Z03|Single Queen Suite Non-Smoking/Refrigerator/Coffeemaker/Microwave/--NFQ1-- Comp Hot Buffet Breakfast
        ///ABEBHA|ABEBHA-Z04|Smoking / 1 King / Handicap Access /Roll-In Shower--SPK1--
        ///ABEBHA|ABEBHA-Z05|Smoking / 1 King / Handicap Access /Kitchenette / Microwav [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HotelDescriptions {
            get {
                return ResourceManager.GetString("HotelDescriptions", resourceCulture);
            }
        }
    }
}
