//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVectorOne.Tests.TBOHolidays {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TBOHolidaysRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TBOHolidaysRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iVectorOne.Tests.TBOHolidays.TBOHolidaysRes", typeof(TBOHolidaysRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: http://api.tbotechnology.in/hotelapi_v7/hotelservice.svc
        ///
        ///**HEADERS**
        ///
        ///Timeout: 100
        ///
        ///
        ///**REQUEST**
        ///
        ///
        ///&lt;soap:Envelope  xmlns:hot=&quot;http://TekTravel/HotelBookingApi&quot; xmlns:wsa=&quot;http://www.w3.org/2005/08/addressing&quot; xmlns:soap=&quot;http://www.w3.org/2003/05/soap-envelope&quot;&gt;
        ///  &lt;soap:Header&gt;
        ///    &lt;hot:Credentials UserName=&quot;testuser&quot; Password=&quot;testpwd&quot; /&gt;
        ///    &lt;wsa:Action&gt;http://TekTravel/HotelBookingApi/HotelSearchWithRooms&lt;/wsa:Action&gt;
        ///    &lt;wsa:To&gt;http://api.tbotechnology.in/hotelapi_v7/hotelservice.sv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLog {
            get {
                return ResourceManager.GetString("RequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;soap:Envelope xmlns:soap=&quot;http://www.w3.org/2003/05/soap-envelope&quot; xmlns:hot=&quot;http://TekTravel/HotelBookingApi&quot; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos;&gt;
        /// &lt;soap:Body&gt;
        ///&lt;hot:HotelSearchWithRoomsResponse&gt;
        /// &lt;hot:Status&gt;
        /// &lt;hot:StatusCode&gt;01&lt;/hot:StatusCode&gt;
        /// &lt;hot:Description&gt;Successful: HotelSearchWithRooms Successful&lt;/hot:Description&gt;
        /// &lt;/hot:Status&gt;
        /// &lt;hot:ResponseTime&gt;21/05/2014 16:52:29&lt;/hot:ResponseTime&gt;
        /// &lt;hot:SessionId&gt;959cd204-6d00-44f4-9aa6-55a886701f69&lt;/hot:SessionId&gt;
        /// &lt;hot:NoOfRoom [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResponseString {
            get {
                return ResourceManager.GetString("ResponseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;CHA1&quot; CC=&quot;USD&quot; PRBID=&quot;1&quot; RT=&quot;Single Room Standard Single&quot; MBC=&quot;RO&quot; AMT=&quot;55.57&quot; TPR=&quot;959cd204-6d00-44f4-9aa6-55a886701f69~~~1~~~1~~~SB|0|0||001:CHA1:8712:S8513:9537:39591|1~~~001:CHA1:8712:S8513:9537:39591|CHA1|SB~~~False,2.65,0,55.57,USD,55.57~~~&quot; DSC=&quot;0&quot; COM=&quot;0&quot; DP=&quot;false&quot; NPA=&quot;0&quot; NRF=&quot;false&quot; FIXPR=&quot;false&quot; FREEC=&quot;false&quot; RQ=&quot;false&quot; PLA=&quot;false&quot; PLR=&quot;false&quot; MSP=&quot;0&quot;&gt;&lt;Cs /&gt;&lt;/Result&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;CHA1&quot; CC=&quot;USD&quot; PRBID=&quot;1&quot; RT=&quot;Single Room Standard Twin&quot; MBC=&quot;RO&quot; AMT=&quot;65.49&quot; TPR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransformedResultXML {
            get {
                return ResourceManager.GetString("TransformedResultXML", resourceCulture);
            }
        }
    }
}
