//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVectorOne.Tests.Juniper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JuniperElevateRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JuniperElevateRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iVectorOne.Tests.Juniper.JuniperElevateRes", typeof(JuniperElevateRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: http://xml-uat.bookingengine.es/webservice/OTA_HotelAvail.asmx
        ///
        ///**HEADERS**
        ///
        ///Timeout: 100
        ///
        ///
        ///**REQUEST**
        ///
        ///&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;soap:Envelope xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///  &lt;soap:Body&gt;
        ///    &lt;OTA_HotelAvailService xmlns=&quot;http://www.opentravel.org/OTA/2003/05&quot;&gt;
        ///      &lt;OTA_HotelAvailRQ PrimaryLangID=&quot;en&quot;&gt;
        ///        &lt;POS&gt;
        ///          &lt;Source AgentDutyCode= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLog {
            get {
                return ResourceManager.GetString("RequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;&lt;soap:Body&gt;&lt;OTA_HotelAvailServiceResponse xmlns=&quot;http://www.opentravel.org/OTA/2003/05&quot;&gt;&lt;OTA_HotelAvailRS TimeStamp=&quot;2022-03-09T09:55:19.2352583+01:00&quot; SequenceNmbr=&quot;Hz0qrtIqUz1iQ4i5NxIWR+9VfAtBBRxQObHm7n4Uj1o=&quot; URL=&quot;http://xml-uat.bookingengine.es/webservice/OTA_HotelAvail.asmx&quot; IntCode=&quot;vInl9Cmq3Nrt7Q0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;JP046300&quot; CC=&quot;USD&quot; RT=&quot;Double&quot; MBC=&quot;3&quot; AMT=&quot;936.17&quot; TPR=&quot;Hz0qrtIqUz1iQ4i5NxIWR+9VfAtBBRxQObHm7n4Uj1o=|ya79dM4dS6R6EywV4XhfEpMj8/i/HX+Jolp81VfcSnkGQQs6X8Ub7Or2U/Yk12lk+KJbXuGP/ezt8JkvlUierKDBuHP/RW22ELEPMIYUUmErNOVzO9FuakAxVi3NS8rUKDsYpRUbvT8vJqryKtdc/bdBEbLVerOVIsgLC1ATpP58TBH2IcZD1NA+KgxCl627tNcpt6EyUZvFQA5Zph4deMtuUmtKI4a6I6swK5jjwbdXZEVsh5R4wBKFOXxXUYmpRlrVCLoaLVRfuVMYmOW9rDy0ie60KEuhAyUgVPKxtQrXIsxL+Q+p2BotzMDT93LhpkAwGkG+/RQv63l893Vy4A==|USD&quot; DSC=&quot;0.00&quot; COM=&quot;0&quot; DP=&quot;false&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransformedResponse {
            get {
                return ResourceManager.GetString("TransformedResponse", resourceCulture);
            }
        }
    }
}
