//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVectorOne.Tests.PremierInn {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PremierInn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PremierInn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iVectorOne.Tests.PremierInn.PremierInn", typeof(PremierInn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: https://tst-polarisapi.avoristravel.com/avail/availability
        ///
        ///**HEADERS**
        ///
        ///Authorization: Basic bmV0OlRlc3ROZXQwMQ==
        ///Timeout: 100
        ///
        ///
        ///**REQUEST**
        ///
        ///{&quot;hotelAvailability&quot;:{&quot;searchAvail&quot;:{&quot;checkIn&quot;:&quot;2021-09-01&quot;,&quot;checkOut&quot;:&quot;2021-09-06&quot;,&quot;destination&quot;:{&quot;hotelCodes&quot;:[&quot;102245&quot;],&quot;location&quot;:{&quot;destinationCode&quot;:&quot;MAD_12&quot;,&quot;type&quot;:&quot;EMPTY&quot;}},&quot;rooms&quot;:[{&quot;index&quot;:1,&quot;passengerAges&quot;:[30]}]}}}
        ///URL: https://tst-polarisapi.avoristravel.com/avail/availability
        ///
        ///**HEADERS**
        ///
        ///Authorization: Basic bmV0OlRlc3ROZXQwMQ==
        ///Tim [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLog {
            get {
                return ResourceManager.GetString("RequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;request&quot;: {
        ///    &quot;hotelAvailability&quot;: {
        ///      &quot;searchAvail&quot;: {
        ///        &quot;checkIn&quot;: &quot;2022-12-28&quot;,
        ///        &quot;checkOut&quot;: &quot;2022-12-29&quot;,
        ///        &quot;rooms&quot;: [{ &quot;passengerAges&quot;: [30, 7, 0], &quot;index&quot;: 1 }],
        ///        &quot;destination&quot;: {
        ///          &quot;hotelCodes&quot;: [&quot;803&quot;],
        ///          &quot;location&quot;: { &quot;destinationCode&quot;: &quot;AVFBK&quot;, &quot;type&quot;: &quot;EMPTY&quot; }
        ///        },
        ///        &quot;market&quot;: &quot;GB&quot;
        ///      },
        ///      &quot;timeout&quot;: 16000,
        ///      &quot;filterAvail&quot;: {}
        ///    },
        ///    &quot;token&quot;: &quot;FULL-DEFAULT-922851-5613720831349870&quot;
        ///  },
        ///  &quot;hotels&quot;: [ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;803&quot; CC=&quot;EUR&quot; RTC=&quot;D&quot; RT=&quot;Doble&quot; MBC=&quot;SA&quot; AMT=&quot;318.31&quot; TPR=&quot;wFn1g/zm0AJpNodzSp3DKL/fb3DWj1x8O0At9qhpeVYvdDpMSR7qeoKyIHdo0V08wlOn1whDBK1f209jjLsk0Q+9G6RGULkcw8222K/ip3S2OBdfwkFQdLO7EBoeRbabiDSBWfHQS6zzfSLUIZ+iSNV+fs9XDo9WBNeBIVuV+wIIYSFJ/SVHYfPZ35cZSg6lH/mc9D84yLIxPz9WRw3ahoXNx74qiB8Yjr+MnEGZfem8Dw8Qw8x7yu0j3v08GaUt&quot; DSC=&quot;0&quot; COM=&quot;0&quot; DP=&quot;false&quot; NRF=&quot;false&quot; FIXPR=&quot;false&quot; SELLPR=&quot;0&quot; NETPR=&quot;0&quot; FREEC=&quot;false&quot; TPRC=&quot;PUBLICA&quot; RQ=&quot;false&quot; PLA=&quot;false&quot; PLR=&quot;false&quot; MSP=&quot;318.31&quot;&gt;&lt;Cs&gt;&lt;C SD=&quot;20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransformedResponse {
            get {
                return ResourceManager.GetString("TransformedResponse", resourceCulture);
            }
        }
    }
}
