//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVectorOne.Tests.PremierInn {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PremierInn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PremierInn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iVectorOne.Tests.PremierInn.PremierInn", typeof(PremierInn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: https://xml.alturaspain.com/xml/xml-interface.php
        ///
        ///**HEADERS**
        ///
        ///Timeout: 100
        ///
        ///
        ///**REQUEST**
        ///
        ///&lt;soapenv:Envelope  xmlns:red=&quot;http://www.redskyit.com&quot; xmlns:soapenv=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;&lt;soapenv:Header /&gt;&lt;soapenv:Body&gt;&lt;red:ProcessMessage&gt;&lt;red:XMLIn&gt;&lt;![CDATA[&lt;Login UserName=&quot;testdiversitytravel&quot; Password=&quot;qtweqwrqwasd&quot;&gt;&lt;/Login&gt;&lt;Parameters MessageType=&quot;AvailabilityRequest&quot;&gt;&lt;HotelCode&gt;102245&lt;/HotelCode&gt;&lt;StayDateRange Start=&quot;2021-09-01&quot; End=&quot;2021-09-06&quot;&gt;&lt;/StayDateRange&gt;&lt;Rooms Nu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLog {
            get {
                return ResourceManager.GetString("RequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;SOAP-ENV:Envelope xmlns:SOAP-ENV=&apos;http://schemas.xmlsoap.org/soap/envelope/&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:s=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;SOAP-ENV:Body&gt;&lt;ProcessMessageResponse xmlns=&quot;http://www.redskyit.com&quot;&gt;&lt;ProcessMessageResult&gt;
        ///&lt;Parameters MessageType=&quot;AvailabilityResponse&quot;&gt;
        ///	&lt;Session ID=&quot;cKBLo7jTO34h0SHm&quot;/&gt;
        ///	&lt;HotelDetails HotelCode=&quot;ABEMAI&quot;&gt;
        ///		&lt;RatePlan RatePlanCode=&quot;RT001&quot;&gt;
        ///			&lt;StatusWarningFlags&gt;
        ///				&lt;Text&gt;There i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;ABEMAI&quot; CC=&quot;GBP&quot; PRBID=&quot;1&quot; RTC=&quot;DBS&quot; RT=&quot;&quot; MBC=&quot;RO&quot; AD=&quot;1&quot; AMT=&quot;436.00&quot; TPR=&quot;qp/kTom5P/8idehm7p+pwyUOidj15F2pLIsKgt1c31Em/7pmxGIHD1vPPMGEV3GJ1gsWRm11zeepKKGL8BXElzeJK9c/4H5K2vkp5HEl8lf7dw87GAKiezxnCn0fziq2PMO2KsQYdBg1pITQF7iCeipwFziAvd2lJbGqpWcl2EtrtxptpORdrtYTaBPfJV24rpPNyPaxNAA+rlLN6r6ekYEGp4DOR/v0oZIHnrJZR/BYbIA31SUGQRL3k2a2TTQM9jc7yE7sZZa7o7ehthB3XdLxioi/f5dpSd0XsMvllEoGFJpZo6VB5c3U47lJQDKdeVnS1/2nmWnUZD891ZEzn1IVeh1Eh4z4OJoL87NfCDiNFWpzwD7zFqW99y4L4ivwJhSwhfjv71Elj1I0uv9Uv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransformedResponse {
            get {
                return ResourceManager.GetString("TransformedResponse", resourceCulture);
            }
        }
    }
}
