//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVectorOne.Tests.Yalago {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class YalagoRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal YalagoRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iVectorOne.Tests.Yalago.YalagoRes", typeof(YalagoRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: https://api.yalago.com/hotels/availability/get
        ///
        ///**HEADERS**
        ///
        ///X-Api-Key: testKey
        ///Accept: application/gzip
        ///Accept-Encoding: gzip
        ///Content-Type: application/json
        ///Timeout: 100
        ///
        ///
        ///**REQUEST**
        ///
        ///{&quot;CheckInDate&quot;:&quot;2021-09-01&quot;,&quot;CheckOutDate&quot;:&quot;2021-09-06&quot;,&quot;LocationId&quot;:0,&quot;EstablishmentIds&quot;:[102245],&quot;Rooms&quot;:[{&quot;Adults&quot;:1,&quot;ChildAges&quot;:[]}],&quot;SourceMarket&quot;:&quot;GB&quot;,&quot;Culture&quot;:&quot;en-gb&quot;,&quot;GetPackagePrice&quot;:false,&quot;GetTaxBreakDown&quot;:true,&quot;GetLocalCharges&quot;:true}
        ///
        ///URL: https://api.yalago.com/hotels/availability/get
        ///
        ///**HE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLogs {
            get {
                return ResourceManager.GetString("RequestLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Establishments&quot;:[{&quot;EstablishmentId&quot;:119606,&quot;Rooms&quot;:[{&quot;Code&quot;:&quot;CE4SBzMyNTEzOTAaBTM0MDM0&quot;,&quot;Description&quot;:&quot;Classic Room&quot;,&quot;QuantityAvailable&quot;:47,&quot;Boards&quot;:[{&quot;Type&quot;:1,&quot;Code&quot;:&quot;CgEx&quot;,&quot;Description&quot;:&quot;Room Only&quot;,&quot;NetCost&quot;:{&quot;Amount&quot;:499.92,&quot;Currency&quot;:&quot;GBP&quot;},&quot;NonRefundable&quot;:false,&quot;IsPayAtHotel&quot;:false,&quot;IsBindingPrice&quot;:false,&quot;IsOnRequest&quot;:false,&quot;RequestedRoomIndex&quot;:0,&quot;CancellationPolicy&quot;:{&quot;CancellationCharges&quot;:[{&quot;Charge&quot;:{&quot;Amount&quot;:99.98,&quot;Currency&quot;:&quot;GBP&quot;,&quot;TaxBreakDown&quot;:{&quot;Amount&quot;:99.98,&quot;Vat&quot;:0.0}},&quot;ExpiryDate&quot;:&quot;2022-02-19T0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;119606&quot; CC=&quot;GBP&quot; PRBID=&quot;1&quot; RTC=&quot;CE4SBzMyNTEzOTAaBTM0MDM0&quot; RT=&quot;Classic Room&quot; MBC=&quot;1&quot; AMT=&quot;499.92&quot; TPR=&quot;119606|CgEx|219522|CE4SBzMyNTEzOTAaBTM0MDM0|False|1&quot; DSC=&quot;0&quot; COM=&quot;0&quot; DP=&quot;false&quot; NPA=&quot;0&quot; NRF=&quot;false&quot; FIXPR=&quot;false&quot; FREEC=&quot;false&quot; RQ=&quot;false&quot; PLA=&quot;false&quot; PLR=&quot;false&quot; MSP=&quot;0&quot;&gt;&lt;Cs&gt;&lt;C SD=&quot;&quot; ED=&quot;&quot; AMT=&quot;0&quot; /&gt;&lt;C SD=&quot;2022-02-19T00:00:00&quot; ED=&quot;2021-09-01T00:00:00&quot; AMT=&quot;20.00&quot; /&gt;&lt;/Cs&gt;&lt;/Result&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;119606&quot; CC=&quot;GBP&quot; PRBID=&quot;1&quot; RTC=&quot;CE4SBzMyNTEzOTAaBTM0MDM1&quot; RT=&quot;Superior Room&quot; M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransformedResponse {
            get {
                return ResourceManager.GetString("TransformedResponse", resourceCulture);
            }
        }
    }
}
