//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVectorOne.Tests.Acerooms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AceroomsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AceroomsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iVectorOne.Tests.Acerooms.AceroomsRes", typeof(AceroomsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: https://stage-gateway.azurewebsites.net/hotel-api/1.0/Search
        ///
        ///**HEADERS**
        ///
        ///APIKey: 19R6dkI20Vgik15aLZ575Xea1
        ///Signature: 243e84e47c43e270c9375a6adc36fd84
        ///Content-Type: application/json
        ///Host: stage-gateway.azurewebsites.net
        ///Content-Length: 148
        ///Expect: 100-continue
        ///Connection: Close
        ///Timeout: 58
        ///
        ///
        ///**REQUEST**
        ///
        ///{&quot;CityID&quot;:3185,&quot;NationalityID&quot;:&quot;115&quot;,&quot;ArrivalDate&quot;:&quot;2021-09-01&quot;,&quot;Nights&quot;:5,&quot;Hotels&quot;:[102245],&quot;CurrencyCode&quot;:&quot;GBP&quot;,&quot;Rooms&quot;:[{&quot;Adult&quot;:1,&quot;Children&quot;:0}]}
        ///
        ///URL: https://stage-gateway.azu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLogs {
            get {
                return ResourceManager.GetString("RequestLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;AuditData&quot;:{&quot;TimeStamp&quot;:&quot;2021/10/19 14:16:26&quot;,&quot;ProcessTime&quot;:&quot;2340&quot;,&quot;RequestHost&quot;:&quot;213.210.61.162&quot;,&quot;SearchToken&quot;:&quot;BAD0349D-88B2-46AB-B547-5AE0C93E7479&quot;},&quot;SearchInfo&quot;:{&quot;CheapestRoom&quot;:false,&quot;ArrivalDate&quot;:&quot;2022-02-27&quot;,&quot;Nights&quot;:5,&quot;Rooms&quot;:[{&quot;Adult&quot;:1,&quot;Children&quot;:0,&quot;RoomNumber&quot;:1}],&quot;CurrencyCode&quot;:&quot;GBP&quot;,&quot;SubAgentID&quot;:0,&quot;CityID&quot;:3185,&quot;CityName&quot;:&quot;London, UK&quot;,&quot;NationalityID&quot;:115,&quot;Nationality&quot;:&quot;Albania&quot;},&quot;Hotels&quot;:[{&quot;HotelID&quot;:87775,&quot;Hotel&quot;:&quot;Park Plaza Park Royal&quot;,&quot;RatingID&quot;:4.0,&quot;Rating&quot;:&quot;4 Star&quot;,&quot;Rooms&quot;:[{&quot;RoomNumber&quot;:1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;87775&quot; CC=&quot;GBP&quot; PRBID=&quot;1&quot; RT=&quot;DOUBLE SUPERIOR KING BED&quot; MBC=&quot;1&quot; AMT=&quot;376.65&quot; TPR=&quot;BAD0349D-88B2-46AB-B547-5AE0C93E7479~2727|161804|DBL.KG-SU|1|1&quot; DSC=&quot;0&quot; COM=&quot;0&quot; DP=&quot;false&quot; NPA=&quot;0&quot; NRF=&quot;false&quot; FIXPR=&quot;false&quot; SELLPR=&quot;376.65&quot; FREEC=&quot;false&quot; RQ=&quot;false&quot; PLA=&quot;false&quot; PLR=&quot;false&quot; MSP=&quot;0&quot;&gt;&lt;Cs&gt;&lt;C SD=&quot;&quot; ED=&quot;&quot; AMT=&quot;0&quot; /&gt;&lt;/Cs&gt;&lt;/Result&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;87775&quot; CC=&quot;GBP&quot; PRBID=&quot;1&quot; RT=&quot;DOUBLE SUPERIOR KING BED&quot; MBC=&quot;2&quot; AMT=&quot;443.91&quot; TPR=&quot;BAD0349D-88B2-46AB-B547-5AE0C93E7479~2727|161804|DBL.KG- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransformedResponse {
            get {
                return ResourceManager.GetString("TransformedResponse", resourceCulture);
            }
        }
    }
}
