//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThirdParty.Tests.DOTW {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DOTWRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DOTWRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThirdParty.Tests.DOTW.DOTWRes", typeof(DOTWRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: http://us.dotwconnect.com/gateway.dotw
        ///
        ///**HEADERS**
        ///
        ///Timeout: -1
        ///
        ///
        ///**REQUEST**
        ///
        ///&lt;customer&gt;
        ///  &lt;username&gt;TestUserName&lt;/username&gt;
        ///  &lt;password&gt;098f6bcd4621d373cade4e832627b4f6&lt;/password&gt;
        ///  &lt;id&gt;672245&lt;/id&gt;
        ///  &lt;source&gt;1&lt;/source&gt;
        ///  &lt;product&gt;hotel&lt;/product&gt;
        ///  &lt;request command=&quot;searchhotels&quot; debug=&quot;0&quot;&gt;
        ///    &lt;bookingDetails&gt;
        ///      &lt;fromDate&gt;2021-09-01&lt;/fromDate&gt;
        ///      &lt;toDate&gt;2021-09-06&lt;/toDate&gt;
        ///      &lt;currency&gt;100&lt;/currency&gt;
        ///      &lt;rooms no=&quot;1&quot;&gt;
        ///        &lt;room runno=&quot;0&quot;&gt;
        ///          &lt;adultsCode [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLog {
            get {
                return ResourceManager.GetString("RequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;result command=&quot;searchhotels&quot; tID=&quot;1638971728107475&quot; ip=&quot;213.210.61.162&quot; date=&quot;2021-12-08 13:55:29&quot; version=&quot;2.0&quot; elapsedTime=&quot;0.88125109672546&quot;&gt;
        ///  &lt;currencyShort&gt;EUR&lt;/currencyShort&gt;
        ///  &lt;hotels count=&quot;4&quot;&gt;
        ///    &lt;hotel runno=&quot;0&quot; preferred=&quot;0&quot; cityname=&quot;CROYDON&quot; order=&quot;3&quot; hotelid=&quot;64524&quot;&gt;
        ///      &lt;hotelName&gt;HILTON CROYDON&lt;/hotelName&gt;
        ///      &lt;noOfRooms&gt;168&lt;/noOfRooms&gt;
        ///      &lt;from&gt;526.3695&lt;formatted&gt;526.37&lt;/formatted&gt;&lt;/from&gt;
        ///      &lt;availability&gt;available&lt;/availability&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;64524&quot; TPK=&quot;64524&quot; CC=&quot;413&quot; PRBID=&quot;1&quot; RT=&quot;TWO DOUBLE BEDS FAMILY ROOM&quot; RTC=&quot;&quot; MBC=&quot;1331&quot; AMT=&quot;835.9987&quot; TPR=&quot;125272855|1331&quot; DP=&quot;1&quot; /&gt;&lt;Result MID=&quot;64524&quot; TPK=&quot;64524&quot; CC=&quot;413&quot; PRBID=&quot;1&quot; RT=&quot;TWO DOUBLE BEDS FAMILY ROOM&quot; RTC=&quot;&quot; MBC=&quot;0&quot; AMT=&quot;769.6496&quot; TPR=&quot;125272855|0&quot; DP=&quot;1&quot; /&gt;&lt;Result MID=&quot;64524&quot; TPK=&quot;64524&quot; CC=&quot;413&quot; PRBID=&quot;1&quot; RT=&quot;TWO DOUBLE BEDS FAMILY ROOM&quot; RTC=&quot;&quot; MBC=&quot;1334&quot; AMT=&quot;1094.7602&quot; TPR=&quot;125272855|1334&quot; DP=&quot;0&quot; /&gt;&lt;Result MID=&quot;64524&quot; TPK=&quot;64524&quot; CC=&quot;413&quot; PRBID=&quot;1&quot; RT=&quot;Presidential [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransformedResponse {
            get {
                return ResourceManager.GetString("TransformedResponse", resourceCulture);
            }
        }
    }
}
