//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThirdParty.Tests.HotelBedsV2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HotelBedsV2Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HotelBedsV2Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThirdParty.Tests.HotelBedsV2.HotelBedsV2Res", typeof(HotelBedsV2Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: https://api.test.hotelbeds.com/hotel-api/1.0/hotels
        ///
        ///**HEADERS**
        ///
        ///Api-key: qgusgu8649g7qz5gbugced7z
        ///X-Signature: 997337791882bf47c0038ed91052c8b71ac291f582487f1ef80856407ce1c9df
        ///Accept: application/json
        ///Accept-Encoding: gzip
        ///Content-Type: application/json
        ///Host: api.test.hotelbeds.com
        ///Content-Length: 425
        ///Connection: Close
        ///Timeout: 58
        ///
        ///
        ///**REQUEST**
        ///
        ///{&quot;stay&quot;:{&quot;checkIn&quot;:&quot;2021-09-01&quot;,&quot;checkOut&quot;:&quot;2021-09-06&quot;,&quot;shiftDays&quot;:null},&quot;occupancies&quot;:[{&quot;rooms&quot;:1,&quot;adults&quot;:1,&quot;children&quot;:0,&quot;paxes&quot;:[{&quot;type&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLog {
            get {
                return ResourceManager.GetString("RequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;auditData&quot;:{&quot;processTime&quot;:&quot;39&quot;,&quot;timestamp&quot;:&quot;2021-08-25 13:21:59.199&quot;,&quot;requestHost&quot;:&quot;213.210.61.162, 35.227.250.134, 35.191.9.175,10.197.40.54,10.197.40.99&quot;,&quot;serverId&quot;:&quot;hotel-booking-api-2-md3x&quot;,&quot;environment&quot;:&quot;[gcpeuropewest1, gcpeuropewest1b, ip_10_197_40_80]&quot;,&quot;release&quot;:&quot;&quot;,&quot;token&quot;:&quot;9AC0DA8A2B8145CBB6135585D6B35A86&quot;,&quot;internal&quot;:&quot;0|FD5DBEA63BE545D162989051916100|UK|05|1|6|1,5||||EUR-0,1000000|Y||||||9||1~1~1~0|0|0||0|qgusgu8649g7qz5gbugced7z||||&quot;},&quot;hotels&quot;:{&quot;hotels&quot;:[{&quot;code&quot;:8526,&quot;name&quot;:&quot;Continental Don Anto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResponseString {
            get {
                return ResourceManager.GetString("ResponseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;8526&quot; CC=&quot;EUR&quot; PRBID=&quot;1&quot; RTC=&quot;DUS.ST&quot; RT=&quot;DOUBLE SINGLE USE STANDARD&quot; MBC=&quot;BB&quot; AMT=&quot;515.35&quot; TPR=&quot;s3kb6HcuosSBPsR4gNPBwoqWlIQbn1Xh/WcTFlhp6MHby9jJA06HXVhl3GOtMgCstENm/WgKrVfmxCL7IUh7c+GEsLXfYFnLQdIzyeEnqlcY1/Ssq+TH1+Xg2RJEhiLGQdFoggg08MOap7dG/tE6wbX7l/g9wlyFS26D6J3sBTUt8yoUeDgDoVQPwjmGUIuM96tuY577Nxm7RQTdtYKNkNcg0wFg0t07qd+ksc652J+RIx2QHwtjxahvUtOWDSgT6LGPA6xOxo6kMJN70c8fCA==&quot; DSC=&quot;0&quot; COM=&quot;0&quot; DP=&quot;false&quot; NPA=&quot;0&quot; NRF=&quot;false&quot; FIXPR=&quot;false&quot; SELLPR=&quot;515.35&quot; NETPR=&quot;515.35&quot; FREEC=&quot;fals [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransformedResultXML {
            get {
                return ResourceManager.GetString("TransformedResultXML", resourceCulture);
            }
        }
    }
}
