//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVectorOne.Tests.HBSi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HBSiRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HBSiRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iVectorOne.Tests.HBSi.HBSiRes", typeof(HBSiRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: https://rhea.demandmatrix.net/app/dm/xml/kenwood
        ///
        ///**HEADERS**
        ///
        ///Timeout: 0
        ///
        ///
        ///**REQUEST**
        ///
        ///&lt;soap-env:Envelope xmlns=&quot;http://www.opentravel.org/OTA/2003/05&quot; xmlns:soap-env=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///  &lt;soap-env:Header&gt;
        ///    &lt;Interface ChannelIdentifierId=&quot;Kenwood_XML4T&quot; Version=&quot;2005A&quot; Interface=&quot;HBSI XML 4 OTA&quot; xmlns=&quot;http://www.hbsiapi.com/Documentation/XML/OTA/4/2005A/&quot;&gt;
        ///      &lt;ComponentInfo Id=&quot;102245&quot; User=&quot;kenwood&quot; Pwd=&quot;xml4t!&quot; ComponentType=&quot;Hotel&quot; /&gt;
        ///    &lt;/Interface&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLog {
            get {
                return ResourceManager.GetString("RequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;soap-env:Envelope xmlns:soap-env=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;&lt;soap-env:Header /&gt;&lt;soap-env:Body RequestId=&quot;20220718044851222&quot; Transaction=&quot;HotelAvailRS&quot;&gt;&lt;OTA_HotelAvailRS TimeStamp=&quot;2022-07-18T13:48:57+00:00&quot; Target=&quot;Test&quot; xmlns=&quot;http://www.opentravel.org/OTA/2003/05&quot;&gt;&lt;Success /&gt;&lt;Warnings&gt;&lt;Warning ShortText=&quot;Not available.&quot;&gt;Property 37958
        ///From 2022-08-27
        ///Until 2022-08-28
        ///Rateplan WWRIONRKRT
        ///Roomtype TBFK
        ///Error NotAvailable
        ///&lt;/Warning&gt;&lt;Warning ShortText=&quot;Not available.&quot;&gt;Property 37958
        ///F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;37958|Kenwood&quot; CC=&quot;USD&quot; PRBID=&quot;1&quot; RT=&quot;Caribbean Luxury Family Sized Suite Double&quot; MBC=&quot;AI&quot; AMT=&quot;1440.0&quot; TPR=&quot;PD|WWRIONRKRT|AI|2|0|0|USD&quot; DSC=&quot;0&quot; COM=&quot;0&quot; DP=&quot;false&quot; NPA=&quot;0&quot; NRF=&quot;false&quot; FIXPR=&quot;false&quot; FREEC=&quot;false&quot; TPRC=&quot;WWRIONRKRT&quot; RQ=&quot;false&quot; PLA=&quot;false&quot; PLR=&quot;false&quot; MSP=&quot;0&quot;&gt;&lt;Cs /&gt;&lt;/Result&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;37958|Kenwood&quot; CC=&quot;USD&quot; PRBID=&quot;1&quot; RT=&quot;Greek Beachfront Concierge Terrace Suite King&quot; MBC=&quot;AI&quot; AMT=&quot;1992.0&quot; TPR=&quot;OTK|WWRIONRKRT|AI|2|0|0|USD&quot; DSC=&quot;0&quot; COM=&quot;0&quot; DP=&quot;false&quot; NPA=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransformedResponse {
            get {
                return ResourceManager.GetString("TransformedResponse", resourceCulture);
            }
        }
    }
}
