//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVectorOne.Tests.HotelsProV2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HotelsProV2Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HotelsProV2Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iVectorOne.Tests.HotelsProV2.HotelsProV2Res", typeof(HotelsProV2Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: https://api2.hotelspro.com/api/v2/search/?checkout=2021-09-06&amp;checkin=2021-09-01&amp;pax=1&amp;hotel_code=102245&amp;client_nationality=US&amp;currency=EUR
        ///
        ///**HEADERS**
        ///
        ///Timeout: 1
        ///
        ///
        ///**REQUEST**
        ///
        ///
        ///
        ///URL: https://api2.hotelspro.com/api/v2/search/?checkout=2021-09-06&amp;checkin=2021-09-01&amp;pax=2&amp;hotel_code=102245&amp;client_nationality=US&amp;currency=EUR
        ///
        ///**HEADERS**
        ///
        ///Timeout: 1
        ///
        ///
        ///**REQUEST**
        ///
        ///
        ///
        ///URL: https://api2.hotelspro.com/api/v2/search/?checkout=2021-09-06&amp;checkin=2021-09-01&amp;pax=1,8&amp;hotel_code=102245&amp;clie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLog {
            get {
                return ResourceManager.GetString("RequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;count&quot;: 1,
        ///  &quot;code&quot;: &quot;20220504_3_2-5-6_1_232_zen11209deec4f64037b23f0650f2fa723d_1647966918&quot;,
        ///  &quot;next_page_code&quot;: null,
        ///  &quot;max_wait&quot;: &quot;7.0&quot;,
        ///  &quot;response_time&quot;: &quot;0.05&quot;,
        ///  &quot;results&quot;: [
        ///    {
        ///      &quot;hotel_code&quot;: &quot;1040e5&quot;,
        ///      &quot;checkin&quot;: &quot;2022-05-04&quot;,
        ///      &quot;checkout&quot;: &quot;2022-05-07&quot;,
        ///      &quot;destination_code&quot;: &quot;15080&quot;,
        ///      &quot;products&quot;: [
        ///        {
        ///          &quot;rooms&quot;: [
        ///            {
        ///              &quot;pax&quot;: { &quot;adult_quantity&quot;: 2, &quot;children_ages&quot;: [5, 6] },
        ///              &quot;room_type&quot;: &quot;QB&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;1040e5&quot; CC=&quot;EUR&quot; PRBID=&quot;1&quot; RT=&quot;Room, 2 Double Beds, Non Smoking&quot; MBC=&quot;RO&quot; AD=&quot;2&quot; AMT=&quot;451.29&quot; TPR=&quot;1040e5|1040e5_530543250_2_108-45_2_2_0_1_530543266_0_4-6-0_2-31_232_2.20220504_3_2-5-6_1_232_zen11209deec4f64037b23f0650f2fa723d_1647966918|20220504_3_2-5-6_1_232_zen11209deec4f64037b23f0650f2fa723d_1647966918&quot; DSC=&quot;0&quot; COM=&quot;0&quot; DP=&quot;false&quot; NPA=&quot;0&quot; NRF=&quot;false&quot; FIXPR=&quot;false&quot; FREEC=&quot;false&quot; RQ=&quot;false&quot; PLA=&quot;false&quot; PLR=&quot;false&quot; MSP=&quot;0&quot;&gt;&lt;Cs /&gt;&lt;/Result&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;1040e5&quot; CC=&quot;EUR&quot; P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransformedResponse {
            get {
                return ResourceManager.GetString("TransformedResponse", resourceCulture);
            }
        }
    }
}
