//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVectorOne.CSSuppliers.AmadeusHotels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AmadeusHotelsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AmadeusHotelsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThirdParty.CSSuppliers.AmadeusHotels.AmadeusHotelsRes", typeof(AmadeusHotelsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;BedTypes&gt;
        ///  &lt;BedType Code=&quot;S&quot; LanguageCode = &quot;en&quot;  BedType=&quot;Single bed&quot;/&gt;
        ///  &lt;BedType Code=&quot;S&quot; LanguageCode = &quot;ar&quot;  BedType=&quot;سرير فردي&quot;/&gt;
        ///  &lt;BedType Code=&quot;S&quot; LanguageCode = &quot;ko&quot;  BedType=&quot;싱글베드&quot;/&gt;
        ///  &lt;BedType Code=&quot;S&quot; LanguageCode = &quot;pt&quot;  BedType=&quot;Cama de solteiro&quot;/&gt;
        ///  &lt;BedType Code=&quot;S&quot; LanguageCode = &quot;es&quot;  BedType=&quot;Cama sencilla&quot;/&gt;
        ///  &lt;BedType Code=&quot;S&quot; LanguageCode = &quot;fr&quot;  BedType=&quot;Lit simple&quot;/&gt;
        ///  &lt;BedType Code=&quot;S&quot; LanguageCode = &quot;ja&quot;  BedType=&quot;シングルベッド&quot;/&gt;
        ///  &lt;Be [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BedTypes {
            get {
                return ResourceManager.GetString("BedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;RoomCategories&gt;
        ///  &lt;RoomCategory Code=&quot;H&quot; LanguageCode = &quot;en&quot;  Category=&quot;Accessible room&quot;/&gt;
        ///  &lt;RoomCategory Code=&quot;H&quot; LanguageCode = &quot;ar&quot;  Category=&quot;غرفة ملائمة لذوي الاحتياجات الخاصة&quot;/&gt;
        ///  &lt;RoomCategory Code=&quot;H&quot; LanguageCode = &quot;ko&quot;  Category=&quot;액세서블룸&quot;/&gt;
        ///  &lt;RoomCategory Code=&quot;H&quot; LanguageCode = &quot;pt&quot;  Category=&quot;Quarto acessível&quot;/&gt;
        ///  &lt;RoomCategory Code=&quot;H&quot; LanguageCode = &quot;es&quot;  Category=&quot;Habitación accesible&quot;/&gt;
        ///  &lt;RoomCategory Code=&quot;H&quot; LanguageCode = &quot;fr&quot;  Category=&quot;Ch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RoomCategories {
            get {
                return ResourceManager.GetString("RoomCategories", resourceCulture);
            }
        }
    }
}
