//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThirdParty.Tests.BedsWithEase {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BedsWithEaseRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BedsWithEaseRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThirdParty.Tests.BedsWithEase.BedsWithEaseRes", typeof(BedsWithEaseRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: http://wsintcli.serhstourism.com/wsserhs/serhstourism
        ///
        ///**HEADERS**
        ///
        ///Content-Type: text/xml
        ///Timeout: 1
        ///
        ///
        ///**REQUEST**
        ///
        ///&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;request type=&quot;ACCOMMODATIONS_AVAIL&quot; version=&quot;4.1&quot;&gt;&lt;client code=&quot;UKTES2&quot; branch=&quot;26293&quot; password=&quot;UKTES2test&quot; tradingGroup=&quot;GBP&quot;/&gt;&lt;language code=&quot;ENG&quot;/&gt;&lt;searchCriteria&gt;&lt;criterion type=&quot;1&quot; code=&quot;accommodationCode&quot; value=&quot;102245&quot;/&gt;&lt;criterion type=&quot;2&quot; code=&quot;priceType&quot; value=&quot;3&quot;/&gt;&lt;/searchCriteria&gt;&lt;period start=&quot;20210901&quot; end=&quot;20210906&quot;/&gt;&lt;rooms&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLog {
            get {
                return ResourceManager.GetString("RequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;S:Envelope xmlns:S=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///  &lt;S:Body&gt;
        ///    &lt;HotelAvailabilityResponse xmlns=&quot;http://topdog.uk.net/BlackBox&quot;&gt;
        ///      &lt;SessionId&gt;5f70434c80f94fee0ea50eef0bbe4639-02100820/A1B&lt;/SessionId&gt;
        ///      &lt;Hotels&gt;
        ///        &lt;Hotel&gt;
        ///          &lt;RoomStays&gt;
        ///            &lt;RoomStay&gt;
        ///              &lt;AllocationVariants&gt;
        ///                &lt;AllocationVariant&gt;
        ///                  &lt;RoomType&gt;
        ///                    &lt;Code/&gt;
        ///                    &lt;Description&gt;AP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResponseXML {
            get {
                return ResourceManager.GetString("ResponseXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;412|10000&quot; CC=&quot;EUR&quot; PRBID=&quot;2&quot; RT=&quot;APARTMENT (1 BEDROOM) STANDARD&quot; MBC=&quot;SC&quot; AMT=&quot;175.79&quot; TPR=&quot;d62e24f95e736fd8f8bb0f258e5c4f56|10000|56.CG-VARIOS|5f70434c80f94fee0ea50eef0bbe4639-02100820/A1B&quot; DSC=&quot;0&quot; AR=&quot;7&quot; COM=&quot;0&quot; DP=&quot;false&quot; NPA=&quot;0&quot; NRF=&quot;false&quot; FIXPR=&quot;false&quot; FREEC=&quot;false&quot; RQ=&quot;false&quot; PLA=&quot;false&quot; PLR=&quot;false&quot; MSP=&quot;0&quot;&gt;&lt;Cs /&gt;&lt;/Result&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;7813|10001&quot; CC=&quot;EUR&quot; PRBID=&quot;1&quot; RT=&quot;BUNGALOW (1 BEDROOM) 3 PEOPLE&quot; MBC=&quot;SC&quot; AMT=&quot;176.82&quot; TPR=&quot;9b4022e1ebbc64555dd3e29d086cb213|100 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransformedResultXML {
            get {
                return ResourceManager.GetString("TransformedResultXML", resourceCulture);
            }
        }
    }
}
