//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVectorOne.Tests.ATI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ATIRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ATIRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iVectorOne.Tests.ATI.ATIRes", typeof(ATIRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: https://xml.alturaspain.com/xml/xml-interface.php
        ///
        ///**HEADERS**
        ///
        ///Timeout: -1
        ///
        ///
        ///**REQUEST**
        ///
        ///&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;soap:Envelope xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:ns1=&quot;http://www.opentravel.org/OTA/2003/05&quot; xmlns=&quot;&quot; xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;&lt;soap:Header /&gt;&lt;soap:Body&gt;&lt;ns1:OTA_HotelAvailRQ Version=&quot;v3&quot;&gt;&lt;POS&gt;&lt;Source ERSP_UserID=&quot;qwcas12g&quot; /&gt;&lt;/POS&gt;&lt;AvailRequestSegments&gt;&lt;AvailRequestS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLog {
            get {
                return ResourceManager.GetString("RequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:ns1=&quot;http://www.opentravel.org/OTA/2003/05&quot;&gt;
        ///    &lt;soap:Header/&gt;
        ///    &lt;soap:Body&gt;
        ///        &lt;ns1:OTA_HotelAvailRS&gt;
        ///            &lt;ns1:RoomStays&gt;
        ///                &lt;ns1:RoomStay&gt;
        ///                    &lt;ns1:BasicPropertyInfo HotelCode=&quot;12&quot; /&gt;
        ///                    &lt;ns1:RoomTypes&gt;
        ///                        &lt;ns1:RoomType RoomTypeCode=&quot;12-14&quot;&gt;
        ///                            &lt;ns1:RoomDescription&gt;
        ///                                &lt;ns1:Text&gt;Room D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResponseXML {
            get {
                return ResourceManager.GetString("ResponseXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;12&quot; CC=&quot;GBP&quot; PRBID=&quot;1&quot; RTC=&quot;12-14&quot; RT=&quot;Room Description 1&quot; MBC=&quot;2399&quot; AD=&quot;1&quot; AMT=&quot;12.5&quot; TPR=&quot;&quot; DSC=&quot;0&quot; COM=&quot;0&quot; DP=&quot;false&quot; NRF=&quot;false&quot; FIXPR=&quot;false&quot; SELLPR=&quot;0&quot; NETPR=&quot;0&quot; FREEC=&quot;false&quot; RQ=&quot;false&quot; PLA=&quot;false&quot; PLR=&quot;false&quot; MSP=&quot;0&quot;&gt;&lt;Adjustments&gt;&lt;Adjustment AT=&quot;Offer&quot; AN=&quot;2 - 4&quot; AA=&quot;0&quot; DSC=&quot;Discount Description 1&quot;&gt;&lt;/Adjustment&gt;&lt;Adjustment AT=&quot;Offer&quot; AN=&quot;6 - 5&quot; AA=&quot;0&quot; DSC=&quot;Discount Description 2&quot;&gt;&lt;/Adjustment&gt;&lt;/Adjustments&gt;&lt;Cs&gt;&lt;C SD=&quot;&quot; AMT=&quot;0&quot;&gt;&lt;/C&gt;&lt;C SD=&quot;&quot; AMT=&quot;12.5&quot;&gt;&lt;/C&gt;&lt;/Cs&gt;&lt;/Result&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransformedResultXML {
            get {
                return ResourceManager.GetString("TransformedResultXML", resourceCulture);
            }
        }
    }
}
