//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVectorOne.Tests.Serhs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SerhsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SerhsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iVectorOne.Tests.Serhs.SerhsRes", typeof(SerhsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: http://wsintcli.serhstourism.com/wsserhs/serhstourism
        ///
        ///**HEADERS**
        ///
        ///Content-Type: text/xml
        ///Timeout: 1
        ///
        ///
        ///**REQUEST**
        ///
        ///&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;request type=&quot;ACCOMMODATIONS_AVAIL&quot; version=&quot;4.1&quot;&gt;&lt;client code=&quot;UKTES2&quot; branch=&quot;26293&quot; password=&quot;UKTES2test&quot; tradingGroup=&quot;GBP&quot;/&gt;&lt;language code=&quot;ENG&quot;/&gt;&lt;searchCriteria&gt;&lt;criterion type=&quot;1&quot; code=&quot;accommodationCode&quot; value=&quot;102245&quot;/&gt;&lt;criterion type=&quot;2&quot; code=&quot;priceType&quot; value=&quot;3&quot;/&gt;&lt;/searchCriteria&gt;&lt;period start=&quot;20210901&quot; end=&quot;20210906&quot;/&gt;&lt;rooms&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLog {
            get {
                return ResourceManager.GetString("RequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;response version=&quot;4.1&quot; type=&quot;ACCOMMODATIONS_AVAIL&quot;&gt;
        ///    &lt;status&gt;0&lt;/status&gt;
        ///    &lt;period end=&quot;20220227&quot; start=&quot;20220222&quot; /&gt;
        ///    &lt;accommodations&gt;
        ///        &lt;accommodation code=&quot;T05382&quot; name=&quot;VILA GALE CERRO ALAGOA&quot; type=&quot;1&quot;&gt;
        ///            &lt;category code=&quot;4&quot; name=&quot;4*&quot; /&gt;
        ///            &lt;city code=&quot;61124&quot; name=&quot;Albufeira&quot; zipCode=&quot;&quot; /&gt;
        ///            &lt;region code=&quot;1831&quot; name=&quot;Algarve&quot; /&gt;
        ///            &lt;country code=&quot;PRT&quot; name=&quot;Portugal&quot; /&gt;
        ///            &lt;area code=&quot;106&quot; name=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;T05382&quot; CC=&quot;EUR&quot; PRBID=&quot;1&quot; RTC=&quot;HE------YZ----&quot; RT=&quot;Standard Room With Views.&quot; MBC=&quot;BB&quot; AMT=&quot;474.81&quot; TPR=&quot;1|BB|D20||H4sIAAAAAAAAAAXBy5ZDMAAA0A-ywDRyWFaFiahJKdPYeYR4nJKjwfj6uReq5pqZsV6i2fJfP16aPDsnCq_4Jj9Klei-x_ibwjEC504m0pzFvkVsMzliz504_UXCsnBAwDWi2ixZ3_LyPCp_O9aaxPe40iASBhCLDg5hjsrKl-Vl_hV8R7TiIEaUboUXpd1JQynnSQM-ztKgZTKocZvP9ppF9hAd6MG-Niqs-WZ0BDhGApFznC2e8sYw00fAoO0PoP7QTs_7vmJettsifju_vM4rMvDM612BmeFi4SZkGtXBkBx8GP4D2-PWLAABAAA=|1|&quot; DSC=&quot;0&quot; COM=&quot;0&quot; DP=&quot;false&quot; NPA=&quot;0&quot; NRF=&quot;f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransformedResponse {
            get {
                return ResourceManager.GetString("TransformedResponse", resourceCulture);
            }
        }
    }
}
