//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThirdParty.Tests.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LeadCustomerRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LeadCustomerRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThirdParty.Tests.Models.LeadCustomerRes", typeof(LeadCustomerRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //plainAddress
        ///plainAddress
        /////noRecipient
        ///@example.com
        /////adressWithUnstandardizedChar
        ///#@%^%#$@#$@#.com
        ///あいうえお@example.com
        /////consecutiveSpecialChars
        ///email..email@example.com
        ///Abc..123@example.com
        ///abc..def@mail.com
        /////emailAppendedAndPrepandedWithSpecialChars
        ///.email@example.com
        ///.abc@mail.com
        ///email@-example.com
        /////invalidTopDomainFormat
        ///email@example
        ///abc.def@mail.c
        ///abc.def@mail..com
        ///abc.def@mail#archive.com.
        /// </summary>
        internal static string InvalidEmailFormats {
            get {
                return ResourceManager.GetString("InvalidEmailFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //standardEmailFormat
        ///email@example.com
        /////emailWithSubDomain
        ///email@subdomain.example.com
        /////longSubdomain
        ///email@123.123.123.123
        /////recipientNameWithNums
        ///1234567890@example.com
        /////dotSplitDomainName
        ///email@example.co.uk
        /////recipientWithSpecialChar
        ///firstname+lastname@example.com
        ///firstname-lastname@example.com
        ///firstname.lastname@example.com
        ///abc-d@mail.com
        ///abc.def@mail.cc
        /////subdomainWithSpecialChar
        ///email@example-one.com
        ///abc.def@mail-archive.com
        /////longTopLevelDomain
        ///email@example.museum
        ///email@exa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidEmailFormats {
            get {
                return ResourceManager.GetString("ValidEmailFormats", resourceCulture);
            }
        }
    }
}
