//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThirdParty.Tests.Travelgate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TravelgateRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TravelgateRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThirdParty.Tests.Travelgate.TravelgateRes", typeof(TravelgateRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: http://hubpublic.xmltravelgate.com/Service/Travel/v2/Hotel.svc
        ///
        ///**HEADERS**
        ///
        ///Content-Type: application/json
        ///Host: intesb.axisdata.net:54321
        ///Content-Length: 798
        ///Expect: 100-continue
        ///Connection: Close
        ///Timeout: 58
        ///
        ///
        ///**REQUEST**
        ///
        ///&lt;soapenv:Envelope xmlns:soapenv = &quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:ns = &quot;http://schemas.xmltravelgate.com/hub/2012/06&quot; xmlns:wsse = &quot;http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd&quot;&gt;&lt;soapenv:Header&gt;&lt;wsse:Security&gt;&lt;ws [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLog {
            get {
                return ResourceManager.GetString("RequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope xmlns:s=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:u=&quot;http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd&quot;&gt;&lt;s:Header&gt;&lt;o:Security s:mustUnderstand=&quot;1&quot; xmlns:o=&quot;http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd&quot;&gt;&lt;u:Timestamp u:Id=&quot;_0&quot;&gt;&lt;u:Created&gt;2021-09-30T11:03:16.632Z&lt;/u:Created&gt;&lt;u:Expires&gt;2021-09-30T11:08:16.632Z&lt;/u:Expires&gt;&lt;/u:Timestamp&gt;&lt;/o:Security&gt;&lt;/s:Header&gt;&lt;s:Body&gt;&lt;AvailResponse xmlns=&quot;http://schemas.xmltravelgate.com/hu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;CS900311&quot; CC=&quot;EUR&quot; PRBID=&quot;1&quot; RTC=&quot;3103&quot; RT=&quot;1 Bedroom apartment with terrace&quot; MBC=&quot;SA&quot; AMT=&quot;511.0&quot; TPR=&quot;1#B0001~3103~1 Bedroom apartment with terrace~MerchantPay~/VomkzrlFQXjl6mtjYJv3vLDglZUI/rB8tBYaQgbGSV2nCb0dfXG3y+VW7fW82ooPZCczzzXlklOwHefFN/1OJGdqCsl7apue8Sz0D1vFGL+kbGoMmnSZUZufhbxNOTRIguph+qdPr4VS+uWU/d3qxpZye9tonVR/sbwH2PeStwrUg7yLyWg2kq/xYcrKczCoOw6P9T/DNOOiYch0qPzBZZHMnNoZS4K00hcKfvibjlvR8uPrX4/Oh4asNYMxkjUNmgQjPok20uHgZJBd3dZHlgGnclSewgCFVjOCYbpW53WNWEezyRN+uhx/AJTWWH6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransformedResponse {
            get {
                return ResourceManager.GetString("TransformedResponse", resourceCulture);
            }
        }
    }
}
