//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVectorOne.Tests.ChannelManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChannelManagerRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChannelManagerRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iVectorOne.Tests.ChannelManager.ChannelManagerRes", typeof(ChannelManagerRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ﻿URL: http://imperatoretestcm.ivector.co.uk/xml/book.ashx
        ///
        ///**HEADERS**
        ///
        ///Accept-Encoding: gzip
        ///Content-Type: application/x-www-form-urlencoded
        ///Host: imperatoretestcm.ivector.co.uk
        ///Content-Length: 2709
        ///Expect: 100-continue
        ///Connection: Close
        ///Timeout: 58
        ///
        ///
        ///**REQUEST**
        ///
        ///&lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;SearchRequest
        ///  xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///  xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;LoginDetails&gt;
        ///    &lt;UserName&gt;iVector&lt;/UserName&gt;
        ///    &lt;Password&gt;ie85dfhuq&lt;/Password&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLog {
            get {
                return ResourceManager.GetString("RequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ﻿&lt;SearchResponse&gt;
        ///  &lt;ReturnStatus&gt;
        ///    &lt;Success&gt;true&lt;/Success&gt;
        ///    &lt;Errors /&gt;
        ///    &lt;Warnings /&gt;
        ///  &lt;/ReturnStatus&gt;
        ///  &lt;Properties&gt;
        ///    &lt;Property&gt;
        ///      &lt;PropertyReferenceID&gt;1266&lt;/PropertyReferenceID&gt;
        ///      &lt;CurrencyID&gt;1&lt;/CurrencyID&gt;
        ///      &lt;ChannelManager&gt;Vertical Booking&lt;/ChannelManager&gt;
        ///      &lt;Rooms&gt;
        ///        &lt;Room&gt;
        ///          &lt;Seq&gt;1&lt;/Seq&gt;
        ///          &lt;RoomBookingToken&gt;15dXgilQnDzr/H6M+Go6VHgOU2gzdL01jziZJ4guI1ueBqUsrMZARpYcqqyw/gvkEnnpJIkTzaIfIIQAJQMlp58ApU2kBBYCdmyzChoJ4yJq60q8X6cZlRhOvYK+RpbpjDq5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResponseString {
            get {
                return ResourceManager.GetString("ResponseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ﻿using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace iVectorOne.Suppliers.TPIntegrationTests.iVectorChannelManager.Resources
        ///{
        ///    class TransformedResultXML
        ///    {
        ///    }
        ///}.
        /// </summary>
        internal static string TransformedResultXML {
            get {
                return ResourceManager.GetString("TransformedResultXML", resourceCulture);
            }
        }
    }
}
