'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class SunHotelsRes
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ThirdParty.VBSuppliers.SunHotelsRes", GetType(SunHotelsRes).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;getRoomTypesResult xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        '''    &lt;roomTypes&gt;
        '''        &lt;roomType&gt;
        '''            &lt;id&gt;1&lt;/id&gt;
        '''            &lt;name&gt;Single room&lt;/name&gt;
        '''            &lt;sharedRoom&gt;0&lt;/sharedRoom&gt;
        '''            &lt;sharedFacilities xsi:nil=&quot;true&quot; /&gt;
        '''        &lt;/roomType&gt;
        '''        &lt;roomType&gt;
        '''            &lt;id&gt;2&lt;/id&gt;
        '''            &lt;name&gt;Single room - Sea View&lt;/name&gt;
        '''            &lt;sharedRoom&gt;0&lt;/sharedRoom&gt;
        '''            &lt;sharedFacilities xsi:nil=&quot;true&quot; /&gt;
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SunHotelsRoomType() As String
            Get
                Return ResourceManager.GetString("SunHotelsRoomType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        '''    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;&gt;
        '''    &lt;xsl:output method=&quot;xml&quot;/&gt;
        '''	&lt;xsl:param name=&quot;Currency&quot; /&gt;
        '''    &lt;xsl:template match=&quot;/&quot;&gt;
        '''    
        '''	&lt;Results&gt;
        '''
        '''		&lt;xsl:for-each select=&quot;/Results/Guests/Room&quot;&gt;
        '''
        '''			&lt;xsl:variable name=&quot;Adults&quot; select=&quot;Adults&quot; /&gt;
        '''			&lt;xsl:variable name=&quot;Children&quot; select=&quot;Children&quot; /&gt;
        '''			&lt;xsl:variable name=&quot;Infants&quot; select= [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SunHotelsSearchXSL() As String
            Get
                Return ResourceManager.GetString("SunHotelsSearchXSL", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
