//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThirdParty.CSSuppliers.Netstorming.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NetstormingRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NetstormingRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThirdParty.CSSuppliers.Netstorming.Resources.NetstormingRes", typeof(NetstormingRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RoomTypeDetails&gt;
        ///    &lt;Contracts&gt;
        ///        &lt;contract contract_id = &quot;19894&quot; name = &quot;BUNGALOW A + COMFORT PACK&quot;/&gt;
        ///        &lt;contract contract_id = &quot;19904&quot; name = &quot;FAMILY PARK SIDE ROOM - 2ADULT+2CHILD(2-11,99)&quot;/&gt;
        ///        &lt;contract contract_id = &quot;19853&quot; name = &quot;1 BEDROOM RESORT APARTMENT&quot;/&gt;
        ///        &lt;contract contract_id = &quot;19854&quot; name = &quot;APARTMENT SUPERIOR - WITH OUTDOOR JACUZZI&quot;/&gt;
        ///        &lt;contract contract_id = &quot;19855&quot; name = &quot;SUPERIOR APARTMENT SEA SIDE VIEW&quot;/&gt;
        ///        &lt;contract contract_id = &quot;19857&quot; n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NetstormingRoomTypes {
            get {
                return ResourceManager.GetString("NetstormingRoomTypes", resourceCulture);
            }
        }
    }
}
