//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThirdParty.Tests.Restel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RestelRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RestelRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThirdParty.Tests.Restel.RestelRes", typeof(RestelRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: http://xml.hotelresb2b.com/xml/listen_xml.jsp?codusu=Codusu&amp;codigousu=Codigousu&amp;clausu=Clausu&amp;afiliacio=RS&amp;secacc=Secacc
        ///
        ///**HEADERS**
        ///
        ///Accept-Encoding: gzip
        ///Content-Type: application/x-www-form-urlencoded
        ///Timeout: 1
        ///
        ///
        ///**REQUEST**
        ///
        ///&lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;peticion&gt;
        ///  &lt;tipo&gt;110&lt;/tipo&gt;
        ///  &lt;parametros&gt;
        ///    &lt;hotel /&gt;
        ///    &lt;pais&gt;MA&lt;/pais&gt;
        ///    &lt;provincia&gt;MAD_12&lt;/provincia&gt;
        ///    &lt;poblacion /&gt;
        ///    &lt;categoria&gt;0&lt;/categoria&gt;
        ///    &lt;radio&gt;0&lt;/radio&gt;
        ///    &lt;fechaentrada&gt;09/01/2021&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLog {
            get {
                return ResourceManager.GetString("RequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;!DOCTYPE respuesta SYSTEM &quot;http://xml.hotelresb2b.com/xml/dtd/res_disponibilidad_110.dtd&quot;&gt;
        ///&lt;respuesta&gt;
        ///	&lt;tipo&gt;&lt;![CDATA[110]]&gt;&lt;/tipo&gt;
        ///	&lt;nombre&gt;&lt;![CDATA[null]]&gt;&lt;/nombre&gt;
        ///	&lt;agencia&gt;&lt;![CDATA[CLUBTRAVEL INTUITIVE XML @]]&gt;&lt;/agencia&gt;
        ///	&lt;param&gt;
        ///		&lt;hotls num=&quot;8&quot;&gt;
        ///			&lt;hot&gt;
        ///				&lt;cod&gt;&lt;![CDATA[789810]]&gt;&lt;/cod&gt;
        ///				&lt;afi&gt;&lt;![CDATA[RS]]&gt;&lt;/afi&gt;
        ///				&lt;nom&gt;&lt;![CDATA[BELVER BOA VISTA HOTEL AND SPA]]&gt;&lt;/nom&gt;
        ///				&lt;pro&gt;&lt;![CDATA[POABU]]&gt;&lt;/pro&gt;
        ///				&lt;prn&gt;&lt;![CDATA[ALBUFEIRA]]&gt;&lt;/prn&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResponseXML {
            get {
                return ResourceManager.GetString("ResponseXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;789810&quot; CC=&quot;EU&quot; RT=&quot;Double/Twin with view&quot; MBC=&quot;BB&quot; AMT=&quot;280.50&quot; TPR=&quot;NzEMFFbe7xWVbbFK4IsY3mNtMBkdYSMU2WdaEdpnazWZ0r/1tWFUXR7WgXLIbpAcwM+FndiwHE/7CeS3zxfgiNxTeNGpKd6KcYg3Gq7/u8lL3U1jL8h93TydZMaR5f4oNj508erWv52QJaG7DoiFW+Gy5kKbh0P7Yp38udjn8Z1x81qa8JgNEnAmTA8vpCbHciKro/9RcIehGPUFYbXE+QVWv/N5nw5bkXOmT+AdePG+OnznSRzobSWpzEVqA/YM05xvlPtLbfJ7EMrf20ZDdrqYwrGxX+Vi8F9TmeI1SyjfYxiBnOleIllp6MiT7Qdt05wMt7SuoRPQ54f2MELv7BpZUbVi3+WBNeOw3pMIwX2ddgEFSLc83IjQf3WQFtfKqd9CWLIA9iiZiUOH6vmnd8EzW0gx [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransformedResultXML {
            get {
                return ResourceManager.GetString("TransformedResultXML", resourceCulture);
            }
        }
    }
}
