//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVectorOne.Suppliers.TPIntegrationTests.Fastpayhotels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FastPayHotelsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FastPayHotelsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThirdParty.Suppliers.TPIntegrationTests.Fastpayhotels.FastpayhotelsRes", typeof(FastPayHotelsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: https://avail.fastpayhotels.net/api/booking/availability
        ///
        ///**HEADERS**
        ///
        ///Content-Type: text/xml
        ///Timeout: 100
        ///
        ///
        ///**REQUEST**
        ///
        ///{&quot;messageID&quot;:&quot;Test1234&quot;,&quot;currency&quot;:&quot;GBP&quot;,&quot;checkIn&quot;:&quot;2021-09-01&quot;,&quot;checkOut&quot;:&quot;2021-09-06&quot;,&quot;occupancies&quot;:[{&quot;adults&quot;:1,&quot;children&quot;:0,&quot;childrenAges&quot;:[]}],&quot;hotelCodes&quot;:[&quot;102245&quot;],&quot;parameters&quot;:{&quot;countryOfResidence&quot;:&quot;GB&quot;,&quot;nationality&quot;:&quot;GB&quot;}}
        ///
        ///URL: https://avail.fastpayhotels.net/api/booking/availability
        ///
        ///**HEADERS**
        ///
        ///Timeout: 100
        ///
        ///
        ///**REQUEST**
        ///
        ///{&quot;messageID&quot;:&quot;Test1234&quot;,&quot;c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLogs {
            get {
                return ResourceManager.GetString("RequestLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;hotelAvails&quot;:[{&quot;hotelInfo&quot;:{&quot;name&quot;:&quot;Days Inn by Wyndham Ridgeland South Carolina&quot;,&quot;category&quot;:{&quot;code&quot;:&quot;2&quot;,&quot;name&quot;:&quot;2 Stars&quot;},&quot;type&quot;:{&quot;code&quot;:&quot;CIT&quot;,&quot;name&quot;:&quot;City&quot;},&quot;code&quot;:&quot;HUS-864XF2HG+46-E00&quot;},&quot;availRoomRates&quot;:[{&quot;reservationToken&quot;:&quot;zZZNbxoxEIb/i8/Y8oy/91Yp10aVml6KUGSvvQlSEtAChwrx3ztedgk5sAcOVRESM/Z48TMz9rtHtmu3rGH2x3f5AI/P8MgWrF3TCEpELh2X8CRlM3zr1OZ6yn+ZOvQ09+vnQw1rL+Y6s8Y51OAWbE3DYcE29HNkMR/e9jvWIIW/rt9yXz5YIz+dby+FZperEw3RFvf9oSzYlv7/1lIKjD1tfXlkbxtaSs/K8c/1fr+g1I2xZcWUTsJqKVdLrwNKTgMGV0stvbHcKYlqtQQFqJEbrd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;HUS-864XF2HG+46-E00&quot; CC=&quot;USD&quot; PRBID=&quot;1&quot; RT=&quot;Double room, 2 Double beds, City view&quot; MBC=&quot;3&quot; AMT=&quot;1629.36&quot; TPR=&quot;zZZNbxoxEIb/i8/Y8oy/91Yp10aVml6KUGSvvQlSEtAChwrx3ztedgk5sAcOVRESM/Z48TMz9rtHtmu3rGH2x3f5AI/P8MgWrF3TCEpELh2X8CRlM3zr1OZ6yn+ZOvQ09+vnQw1rL+Y6s8Y51OAWbE3DYcE29HNkMR/e9jvWIIW/rt9yXz5YIz+dby+FZperEw3RFvf9oSzYlv7/1lIKjD1tfXlkbxtaSs/K8c/1fr+g1I2xZcWUTsJqKVdLrwNKTgMGV0stvbHcKYlqtQQFqJEbrdSK+F4Ow2rlTMKggOcInusudzwENFwnhbq0CVvbUnRMe9Z4EM6QHckOKJSn3a135EhBG32P/QtrVDXbTR0dQz5KtY1A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransformedResponse {
            get {
                return ResourceManager.GetString("TransformedResponse", resourceCulture);
            }
        }
    }
}
