//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThirdParty.Tests.YouTravel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class YouTravelRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal YouTravelRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThirdParty.Tests.YouTravel.YouTravelRes", typeof(YouTravelRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: http://testxml.youtravel.com/webservicestest/index.asp?HID=102245&amp;LangID=EN&amp;Username=xmltestme&amp;Password=testme&amp;Checkin_Date=01/09/2021&amp;Nights=5&amp;Rooms=1&amp;ADLTS_1=1&amp;CanxPol=1
        ///
        ///**HEADERS**
        ///
        ///Timeout: 58
        ///
        ///
        ///**REQUEST**
        ///
        ///URL: http://testxml.youtravel.com/webservicestest/index.asp?HID=102245&amp;LangID=EN&amp;Username=xmltestme&amp;Password=testme&amp;Checkin_Date=01/09/2021&amp;Nights=5&amp;Rooms=1&amp;ADLTS_1=2&amp;CanxPol=1
        ///
        ///**HEADERS**
        ///
        ///Timeout: 58
        ///
        ///
        ///**REQUEST**
        ///
        ///URL: http://testxml.youtravel.com/webservicestest/index.as [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLog {
            get {
                return ResourceManager.GetString("RequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;ISO-8859-1&apos;?&gt;
        ///&lt;HtSearchRq xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xsi:noNamespaceSchemaLocation=&apos;http://xml.youtravel.com/webservices/xsd_yt_srq.xsd&apos;&gt;
        ///&lt;Success&gt;true&lt;/Success&gt;
        ///&lt;Search_Criteria&gt;
        ///&lt;Company&gt;XML Test Affiliate&lt;/Company&gt;
        ///&lt;LangID&gt;EN&lt;/LangID&gt;
        ///&lt;Dstn&gt;&lt;/Dstn&gt;
        ///&lt;Rsrt&gt;8824&lt;/Rsrt&gt;
        ///&lt;Rooms&gt;1&lt;/Rooms&gt;
        ///&lt;Nofn&gt;5&lt;/Nofn&gt;
        ///&lt;Checkin_Date&gt;01/09/2021&lt;/Checkin_Date&gt;
        ///&lt;Youtravel_Rating&gt;All star ratings&lt;/Youtravel_Rating&gt;
        ///&lt;Board_Type&gt;1&lt;/Board_Type&gt;
        ///&lt;Adlts_1&gt;1&lt;/Adlts_1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResponseString {
            get {
                return ResourceManager.GetString("ResponseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;1572&quot; CC=&quot;EUR&quot; PRBID=&quot;1&quot; RT=&quot;Standard Room&quot; RTC=&quot;0&quot; MBC=&quot;BB&quot; AD=&quot;0&quot; CH=&quot;0&quot; hlpCHA=&quot;0&quot; INF=&quot;0&quot; AMT=&quot;228.7&quot; TPR=&quot;1086313642203202125424114|1158562|yytdtbeaeedgqaiaepeypjpyaeapatapaepp&quot; NRF=&quot;0&quot; /&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;1572&quot; CC=&quot;EUR&quot; PRBID=&quot;1&quot; RT=&quot;Standard Room&quot; RTC=&quot;0&quot; MBC=&quot;HB&quot; AD=&quot;0&quot; CH=&quot;0&quot; hlpCHA=&quot;0&quot; INF=&quot;0&quot; AMT=&quot;343.05&quot; TPR=&quot;1086313642203202125424114|1158563|yytdtbwawiwgptaiaepeypjpyaeapatapawpp&quot; NRF=&quot;0&quot; /&gt;&lt;Result MID=&quot;0&quot; TPK=&quot;1572&quot; CC=&quot;EUR&quot; PRBID=&quot;1&quot; RT=&quot;Standard Room&quot; RTC=&quot;0&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransformedResponseXML {
            get {
                return ResourceManager.GetString("TransformedResponseXML", resourceCulture);
            }
        }
    }
}
