//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThirdParty.Tests.Altura {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AlturaRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlturaRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThirdParty.Tests.Altura.AlturaRes", typeof(AlturaRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: https://xml.alturaspain.com/xml/xml-interface.php
        ///
        ///**HEADERS**
        ///
        ///Timeout: 1
        ///
        ///
        ///**REQUEST**
        ///
        ///&lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;AlturaDS_requests&gt;
        ///  &lt;Request type=&quot;Availability&quot; version=&quot;v2.8.3&quot; currency=&quot;EUR&quot;&gt;
        ///    &lt;Session&gt;
        ///      &lt;AgencyId&gt;100&lt;/AgencyId&gt;
        ///      &lt;Password&gt;3141592&lt;/Password&gt;
        ///      &lt;ExternalId&gt;test&lt;/ExternalId&gt;
        ///    &lt;/Session&gt;
        ///    &lt;Destination type=&quot;HOTEL&quot;&gt;102245&lt;/Destination&gt;
        ///    &lt;Arrival&gt;20210901&lt;/Arrival&gt;
        ///    &lt;Departure&gt;20210906&lt;/Departure&gt;
        ///    &lt;NumberOfRooms&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLog {
            get {
                return ResourceManager.GetString("RequestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;AlturaDS_responses&gt;
        ///    &lt;Response type=&quot;Availability&quot; session=&quot;201403191132301157890017&quot;&gt;
        ///        &lt;Session&gt;
        ///            &lt;AgencyId&gt;100&lt;/AgencyId&gt;
        ///            &lt;ExternalId&gt;&lt;/ExternalId&gt;
        ///        &lt;/Session&gt;
        ///        &lt;Hotels&gt;
        ///            &lt;Hotel id=&quot;838&quot;&gt;
        ///                &lt;Name&gt;&lt;!--[CDATA[Intertur Waikiki Apts.]]--&gt;&lt;/Name&gt;
        ///                &lt;Rating&gt;3k&lt;/Rating&gt;
        ///                &lt;Resort&gt;34-07-PMI-001&lt;/Resort&gt;
        ///                &lt;ResortName&gt;&lt;!--[CDATA[Palma Nova]]--&gt;&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Result MID=&quot;838&quot; TPK=&quot;838&quot; CC=&quot;EUR&quot; RTC=&quot;29&quot; RT=&quot;1 Bedroom Apt&quot; MBC=&quot;AI&quot; AMT=&quot;1432.34&quot; TPR=&quot;|26967496&quot; DSC=&quot;0&quot; COM=&quot;0&quot; DP=&quot;false&quot; NPA=&quot;0&quot; NRF=&quot;false&quot; FIXPR=&quot;false&quot; FREEC=&quot;false&quot; RQ=&quot;false&quot; PLA=&quot;false&quot; PLR=&quot;false&quot; MSP=&quot;0&quot;&gt;&lt;Cs /&gt;&lt;/Result&gt;&lt;Result MID=&quot;838&quot; TPK=&quot;838&quot; CC=&quot;EUR&quot; RTC=&quot;29&quot; RT=&quot;1 Bedroom Apt&quot; MBC=&quot;BB&quot; AMT=&quot;758.94&quot; TPR=&quot;|26967497&quot; DSC=&quot;0&quot; COM=&quot;0&quot; DP=&quot;false&quot; NPA=&quot;0&quot; NRF=&quot;false&quot; FIXPR=&quot;false&quot; FREEC=&quot;false&quot; RQ=&quot;false&quot; PLA=&quot;false&quot; PLR=&quot;false&quot; MSP=&quot;0&quot;&gt;&lt;Cs /&gt;&lt;/Result&gt;&lt;Result MID=&quot;1950&quot; TPK=&quot;1950&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransformedResponse {
            get {
                return ResourceManager.GetString("TransformedResponse", resourceCulture);
            }
        }
    }
}
