namespace iVectorOne.Models.Tokens
{
    public enum TokenValueType
    {
        PropertyID,
        Year,
        Month,
        Day,
        Duration,
        Hour1,
        Minute1,
        Hour2,
        Minute2,
        Adults,
        Children,
        Infants,
        Rooms,
        ChildAge1,
        ChildAge2,
        ChildAge3,
        ChildAge4,
        ChildAge5,
        ChildAge6,
        ChildAge7,
        ChildAge8,
        PropertyRoomBookingID, 
        CurrencyID,
        MealBasisID,
        LocalCost1,
        LocalCost2, 
        SupplierID, 
        OneWay
    }
}