namespace ThirdParty.Models.Tokens
{
    public enum TokenValueType
    {
        PropertyID,
        Year,
        Month,
        Day,
        Duration,
        Adults,
        Children,
        Infants,
        Rooms,
        ChildAge1,
        ChildAge2,
        ChildAge3,
        ChildAge4,
        ChildAge5,
        ChildAge6,
        ChildAge7,
        ChildAge8,
        PropertyRoomBookingID, 
        CurrencyID,
        MealBasisID1,
        MealBasisID2,
        MealBasisID3,
        LocalCost1,
        LocalCost2
    }
}